/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Activity
 */
@JacksonXmlRootElement(localName = "Activity")
@XmlRootElement(name = "Activity")
@XmlAccessorType(XmlAccessType.FIELD)
public class Activity implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("ACTIVITY_ID")
  @JacksonXmlProperty(localName = "ACTIVITY_ID")
  @XmlElement(name = "ACTIVITY_ID")
  private Long ACTIVITY_ID = null;

  @JsonProperty("ACTIVITYSET_ID")
  @JacksonXmlProperty(localName = "ACTIVITYSET_ID")
  @XmlElement(name = "ACTIVITYSET_ID")
  private Long ACTIVITYSET_ID = null;

  @JsonProperty("ACTIVITY_NAME")
  @JacksonXmlProperty(localName = "ACTIVITY_NAME")
  @XmlElement(name = "ACTIVITY_NAME")
  private String ACTIVITY_NAME = null;

  @JsonProperty("ACTIVITY_DETAILS")
  @JacksonXmlProperty(localName = "ACTIVITY_DETAILS")
  @XmlElement(name = "ACTIVITY_DETAILS")
  private String ACTIVITY_DETAILS = null;

  @JsonProperty("ACTIVITY_TYPE")
  @JacksonXmlProperty(localName = "ACTIVITY_TYPE")
  @XmlElement(name = "ACTIVITY_TYPE")
  private String ACTIVITY_TYPE = null;

  @JsonProperty("CATEGORY_ID")
  @JacksonXmlProperty(localName = "CATEGORY_ID")
  @XmlElement(name = "CATEGORY_ID")
  private Long CATEGORY_ID = null;

  @JsonProperty("REMINDER")
  @JacksonXmlProperty(localName = "REMINDER")
  @XmlElement(name = "REMINDER")
  private Boolean REMINDER = null;

  @JsonProperty("REMINDER_DAYS_BEFORE_DUE")
  @JacksonXmlProperty(localName = "REMINDER_DAYS_BEFORE_DUE")
  @XmlElement(name = "REMINDER_DAYS_BEFORE_DUE")
  private Integer REMINDER_DAYS_BEFORE_DUE = null;

  @JsonProperty("REMINDER_TIME")
  @JacksonXmlProperty(localName = "REMINDER_TIME")
  @XmlElement(name = "REMINDER_TIME")
  private String REMINDER_TIME = null;

  @JsonProperty("PUBLICLY_VISIBLE")
  @JacksonXmlProperty(localName = "PUBLICLY_VISIBLE")
  @XmlElement(name = "PUBLICLY_VISIBLE")
  private Boolean PUBLICLY_VISIBLE = null;

  @JsonProperty("OWNER_VISIBLE")
  @JacksonXmlProperty(localName = "OWNER_VISIBLE")
  @XmlElement(name = "OWNER_VISIBLE")
  private Boolean OWNER_VISIBLE = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("RESPONSIBLE_USER_ID")
  @JacksonXmlProperty(localName = "RESPONSIBLE_USER_ID")
  @XmlElement(name = "RESPONSIBLE_USER_ID")
  private Integer RESPONSIBLE_USER_ID = null;

  @JsonProperty("ASSIGNED_TEAM_ID")
  @JacksonXmlProperty(localName = "ASSIGNED_TEAM_ID")
  @XmlElement(name = "ASSIGNED_TEAM_ID")
  private Long ASSIGNED_TEAM_ID = null;

  @JsonProperty("SKIP_SUN")
  @JacksonXmlProperty(localName = "SKIP_SUN")
  @XmlElement(name = "SKIP_SUN")
  private Boolean SKIP_SUN = null;

  @JsonProperty("SKIP_MON")
  @JacksonXmlProperty(localName = "SKIP_MON")
  @XmlElement(name = "SKIP_MON")
  private Boolean SKIP_MON = null;

  @JsonProperty("SKIP_TUE")
  @JacksonXmlProperty(localName = "SKIP_TUE")
  @XmlElement(name = "SKIP_TUE")
  private Boolean SKIP_TUE = null;

  @JsonProperty("SKIP_WED")
  @JacksonXmlProperty(localName = "SKIP_WED")
  @XmlElement(name = "SKIP_WED")
  private Boolean SKIP_WED = null;

  @JsonProperty("SKIP_THU")
  @JacksonXmlProperty(localName = "SKIP_THU")
  @XmlElement(name = "SKIP_THU")
  private Boolean SKIP_THU = null;

  @JsonProperty("SKIP_FRI")
  @JacksonXmlProperty(localName = "SKIP_FRI")
  @XmlElement(name = "SKIP_FRI")
  private Boolean SKIP_FRI = null;

  @JsonProperty("SKIP_SAT")
  @JacksonXmlProperty(localName = "SKIP_SAT")
  @XmlElement(name = "SKIP_SAT")
  private Boolean SKIP_SAT = null;

  @JsonProperty("DUE_DAYS_AFTER_START")
  @JacksonXmlProperty(localName = "DUE_DAYS_AFTER_START")
  @XmlElement(name = "DUE_DAYS_AFTER_START")
  private Integer DUE_DAYS_AFTER_START = null;

  @JsonProperty("DUE_DAYS_BEFORE_END")
  @JacksonXmlProperty(localName = "DUE_DAYS_BEFORE_END")
  @XmlElement(name = "DUE_DAYS_BEFORE_END")
  private Integer DUE_DAYS_BEFORE_END = null;

  @JsonProperty("EVENT_DAYS_AFTER_START")
  @JacksonXmlProperty(localName = "EVENT_DAYS_AFTER_START")
  @XmlElement(name = "EVENT_DAYS_AFTER_START")
  private Integer EVENT_DAYS_AFTER_START = null;

  @JsonProperty("EVENT_DAYS_BEFORE_END")
  @JacksonXmlProperty(localName = "EVENT_DAYS_BEFORE_END")
  @XmlElement(name = "EVENT_DAYS_BEFORE_END")
  private Integer EVENT_DAYS_BEFORE_END = null;

  @JsonProperty("EVENT_TIME")
  @JacksonXmlProperty(localName = "EVENT_TIME")
  @XmlElement(name = "EVENT_TIME")
  private String EVENT_TIME = null;

  @JsonProperty("ALL_DAY")
  @JacksonXmlProperty(localName = "ALL_DAY")
  @XmlElement(name = "ALL_DAY")
  private Boolean ALL_DAY = null;

  @JsonProperty("DURATION")
  @JacksonXmlProperty(localName = "DURATION")
  @XmlElement(name = "DURATION")
  private Integer DURATION = null;

  public Activity ACTIVITY_ID(Long ACTIVITY_ID) {
    this.ACTIVITY_ID = ACTIVITY_ID;
    return this;
  }

   /**
   * Get ACTIVITY_ID
   * @return ACTIVITY_ID
  **/
  
  public Long getACTIVITYID() {
    return ACTIVITY_ID;
  }

  public void setACTIVITYID(Long ACTIVITY_ID) {
    this.ACTIVITY_ID = ACTIVITY_ID;
  }

  public Activity ACTIVITYSET_ID(Long ACTIVITYSET_ID) {
    this.ACTIVITYSET_ID = ACTIVITYSET_ID;
    return this;
  }

   /**
   * Get ACTIVITYSET_ID
   * @return ACTIVITYSET_ID
  **/
  
  public Long getACTIVITYSETID() {
    return ACTIVITYSET_ID;
  }

  public void setACTIVITYSETID(Long ACTIVITYSET_ID) {
    this.ACTIVITYSET_ID = ACTIVITYSET_ID;
  }

  public Activity ACTIVITY_NAME(String ACTIVITY_NAME) {
    this.ACTIVITY_NAME = ACTIVITY_NAME;
    return this;
  }

   /**
   * Get ACTIVITY_NAME
   * @return ACTIVITY_NAME
  **/
  
  public String getACTIVITYNAME() {
    return ACTIVITY_NAME;
  }

  public void setACTIVITYNAME(String ACTIVITY_NAME) {
    this.ACTIVITY_NAME = ACTIVITY_NAME;
  }

  public Activity ACTIVITY_DETAILS(String ACTIVITY_DETAILS) {
    this.ACTIVITY_DETAILS = ACTIVITY_DETAILS;
    return this;
  }

   /**
   * Get ACTIVITY_DETAILS
   * @return ACTIVITY_DETAILS
  **/
  
  public String getACTIVITYDETAILS() {
    return ACTIVITY_DETAILS;
  }

  public void setACTIVITYDETAILS(String ACTIVITY_DETAILS) {
    this.ACTIVITY_DETAILS = ACTIVITY_DETAILS;
  }

  public Activity ACTIVITY_TYPE(String ACTIVITY_TYPE) {
    this.ACTIVITY_TYPE = ACTIVITY_TYPE;
    return this;
  }

   /**
   * Get ACTIVITY_TYPE
   * @return ACTIVITY_TYPE
  **/
  
  public String getACTIVITYTYPE() {
    return ACTIVITY_TYPE;
  }

  public void setACTIVITYTYPE(String ACTIVITY_TYPE) {
    this.ACTIVITY_TYPE = ACTIVITY_TYPE;
  }

  public Activity CATEGORY_ID(Long CATEGORY_ID) {
    this.CATEGORY_ID = CATEGORY_ID;
    return this;
  }

   /**
   * Get CATEGORY_ID
   * @return CATEGORY_ID
  **/
  
  public Long getCATEGORYID() {
    return CATEGORY_ID;
  }

  public void setCATEGORYID(Long CATEGORY_ID) {
    this.CATEGORY_ID = CATEGORY_ID;
  }

  public Activity REMINDER(Boolean REMINDER) {
    this.REMINDER = REMINDER;
    return this;
  }

   /**
   * Get REMINDER
   * @return REMINDER
  **/
  
  public Boolean getREMINDER() {
    return REMINDER;
  }

  public void setREMINDER(Boolean REMINDER) {
    this.REMINDER = REMINDER;
  }

  public Activity REMINDER_DAYS_BEFORE_DUE(Integer REMINDER_DAYS_BEFORE_DUE) {
    this.REMINDER_DAYS_BEFORE_DUE = REMINDER_DAYS_BEFORE_DUE;
    return this;
  }

   /**
   * Get REMINDER_DAYS_BEFORE_DUE
   * @return REMINDER_DAYS_BEFORE_DUE
  **/
  
  public Integer getREMINDERDAYSBEFOREDUE() {
    return REMINDER_DAYS_BEFORE_DUE;
  }

  public void setREMINDERDAYSBEFOREDUE(Integer REMINDER_DAYS_BEFORE_DUE) {
    this.REMINDER_DAYS_BEFORE_DUE = REMINDER_DAYS_BEFORE_DUE;
  }

  public Activity REMINDER_TIME(String REMINDER_TIME) {
    this.REMINDER_TIME = REMINDER_TIME;
    return this;
  }

   /**
   * Get REMINDER_TIME
   * @return REMINDER_TIME
  **/
  
  public String getREMINDERTIME() {
    return REMINDER_TIME;
  }

  public void setREMINDERTIME(String REMINDER_TIME) {
    this.REMINDER_TIME = REMINDER_TIME;
  }

  public Activity PUBLICLY_VISIBLE(Boolean PUBLICLY_VISIBLE) {
    this.PUBLICLY_VISIBLE = PUBLICLY_VISIBLE;
    return this;
  }

   /**
   * Get PUBLICLY_VISIBLE
   * @return PUBLICLY_VISIBLE
  **/
  
  public Boolean getPUBLICLYVISIBLE() {
    return PUBLICLY_VISIBLE;
  }

  public void setPUBLICLYVISIBLE(Boolean PUBLICLY_VISIBLE) {
    this.PUBLICLY_VISIBLE = PUBLICLY_VISIBLE;
  }

  public Activity OWNER_VISIBLE(Boolean OWNER_VISIBLE) {
    this.OWNER_VISIBLE = OWNER_VISIBLE;
    return this;
  }

   /**
   * Get OWNER_VISIBLE
   * @return OWNER_VISIBLE
  **/
  
  public Boolean getOWNERVISIBLE() {
    return OWNER_VISIBLE;
  }

  public void setOWNERVISIBLE(Boolean OWNER_VISIBLE) {
    this.OWNER_VISIBLE = OWNER_VISIBLE;
  }

  public Activity OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public Activity RESPONSIBLE_USER_ID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
    return this;
  }

   /**
   * Get RESPONSIBLE_USER_ID
   * @return RESPONSIBLE_USER_ID
  **/
  
  public Integer getRESPONSIBLEUSERID() {
    return RESPONSIBLE_USER_ID;
  }

  public void setRESPONSIBLEUSERID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
  }

  public Activity ASSIGNED_TEAM_ID(Long ASSIGNED_TEAM_ID) {
    this.ASSIGNED_TEAM_ID = ASSIGNED_TEAM_ID;
    return this;
  }

   /**
   * Get ASSIGNED_TEAM_ID
   * @return ASSIGNED_TEAM_ID
  **/
  
  public Long getASSIGNEDTEAMID() {
    return ASSIGNED_TEAM_ID;
  }

  public void setASSIGNEDTEAMID(Long ASSIGNED_TEAM_ID) {
    this.ASSIGNED_TEAM_ID = ASSIGNED_TEAM_ID;
  }

  public Activity SKIP_SUN(Boolean SKIP_SUN) {
    this.SKIP_SUN = SKIP_SUN;
    return this;
  }

   /**
   * Get SKIP_SUN
   * @return SKIP_SUN
  **/
  
  public Boolean getSKIPSUN() {
    return SKIP_SUN;
  }

  public void setSKIPSUN(Boolean SKIP_SUN) {
    this.SKIP_SUN = SKIP_SUN;
  }

  public Activity SKIP_MON(Boolean SKIP_MON) {
    this.SKIP_MON = SKIP_MON;
    return this;
  }

   /**
   * Get SKIP_MON
   * @return SKIP_MON
  **/
  
  public Boolean getSKIPMON() {
    return SKIP_MON;
  }

  public void setSKIPMON(Boolean SKIP_MON) {
    this.SKIP_MON = SKIP_MON;
  }

  public Activity SKIP_TUE(Boolean SKIP_TUE) {
    this.SKIP_TUE = SKIP_TUE;
    return this;
  }

   /**
   * Get SKIP_TUE
   * @return SKIP_TUE
  **/
  
  public Boolean getSKIPTUE() {
    return SKIP_TUE;
  }

  public void setSKIPTUE(Boolean SKIP_TUE) {
    this.SKIP_TUE = SKIP_TUE;
  }

  public Activity SKIP_WED(Boolean SKIP_WED) {
    this.SKIP_WED = SKIP_WED;
    return this;
  }

   /**
   * Get SKIP_WED
   * @return SKIP_WED
  **/
  
  public Boolean getSKIPWED() {
    return SKIP_WED;
  }

  public void setSKIPWED(Boolean SKIP_WED) {
    this.SKIP_WED = SKIP_WED;
  }

  public Activity SKIP_THU(Boolean SKIP_THU) {
    this.SKIP_THU = SKIP_THU;
    return this;
  }

   /**
   * Get SKIP_THU
   * @return SKIP_THU
  **/
  
  public Boolean getSKIPTHU() {
    return SKIP_THU;
  }

  public void setSKIPTHU(Boolean SKIP_THU) {
    this.SKIP_THU = SKIP_THU;
  }

  public Activity SKIP_FRI(Boolean SKIP_FRI) {
    this.SKIP_FRI = SKIP_FRI;
    return this;
  }

   /**
   * Get SKIP_FRI
   * @return SKIP_FRI
  **/
  
  public Boolean getSKIPFRI() {
    return SKIP_FRI;
  }

  public void setSKIPFRI(Boolean SKIP_FRI) {
    this.SKIP_FRI = SKIP_FRI;
  }

  public Activity SKIP_SAT(Boolean SKIP_SAT) {
    this.SKIP_SAT = SKIP_SAT;
    return this;
  }

   /**
   * Get SKIP_SAT
   * @return SKIP_SAT
  **/
  
  public Boolean getSKIPSAT() {
    return SKIP_SAT;
  }

  public void setSKIPSAT(Boolean SKIP_SAT) {
    this.SKIP_SAT = SKIP_SAT;
  }

  public Activity DUE_DAYS_AFTER_START(Integer DUE_DAYS_AFTER_START) {
    this.DUE_DAYS_AFTER_START = DUE_DAYS_AFTER_START;
    return this;
  }

   /**
   * Get DUE_DAYS_AFTER_START
   * @return DUE_DAYS_AFTER_START
  **/
  
  public Integer getDUEDAYSAFTERSTART() {
    return DUE_DAYS_AFTER_START;
  }

  public void setDUEDAYSAFTERSTART(Integer DUE_DAYS_AFTER_START) {
    this.DUE_DAYS_AFTER_START = DUE_DAYS_AFTER_START;
  }

  public Activity DUE_DAYS_BEFORE_END(Integer DUE_DAYS_BEFORE_END) {
    this.DUE_DAYS_BEFORE_END = DUE_DAYS_BEFORE_END;
    return this;
  }

   /**
   * Get DUE_DAYS_BEFORE_END
   * @return DUE_DAYS_BEFORE_END
  **/
  
  public Integer getDUEDAYSBEFOREEND() {
    return DUE_DAYS_BEFORE_END;
  }

  public void setDUEDAYSBEFOREEND(Integer DUE_DAYS_BEFORE_END) {
    this.DUE_DAYS_BEFORE_END = DUE_DAYS_BEFORE_END;
  }

  public Activity EVENT_DAYS_AFTER_START(Integer EVENT_DAYS_AFTER_START) {
    this.EVENT_DAYS_AFTER_START = EVENT_DAYS_AFTER_START;
    return this;
  }

   /**
   * Get EVENT_DAYS_AFTER_START
   * @return EVENT_DAYS_AFTER_START
  **/
  
  public Integer getEVENTDAYSAFTERSTART() {
    return EVENT_DAYS_AFTER_START;
  }

  public void setEVENTDAYSAFTERSTART(Integer EVENT_DAYS_AFTER_START) {
    this.EVENT_DAYS_AFTER_START = EVENT_DAYS_AFTER_START;
  }

  public Activity EVENT_DAYS_BEFORE_END(Integer EVENT_DAYS_BEFORE_END) {
    this.EVENT_DAYS_BEFORE_END = EVENT_DAYS_BEFORE_END;
    return this;
  }

   /**
   * Get EVENT_DAYS_BEFORE_END
   * @return EVENT_DAYS_BEFORE_END
  **/
  
  public Integer getEVENTDAYSBEFOREEND() {
    return EVENT_DAYS_BEFORE_END;
  }

  public void setEVENTDAYSBEFOREEND(Integer EVENT_DAYS_BEFORE_END) {
    this.EVENT_DAYS_BEFORE_END = EVENT_DAYS_BEFORE_END;
  }

  public Activity EVENT_TIME(String EVENT_TIME) {
    this.EVENT_TIME = EVENT_TIME;
    return this;
  }

   /**
   * Get EVENT_TIME
   * @return EVENT_TIME
  **/
  
  public String getEVENTTIME() {
    return EVENT_TIME;
  }

  public void setEVENTTIME(String EVENT_TIME) {
    this.EVENT_TIME = EVENT_TIME;
  }

  public Activity ALL_DAY(Boolean ALL_DAY) {
    this.ALL_DAY = ALL_DAY;
    return this;
  }

   /**
   * Get ALL_DAY
   * @return ALL_DAY
  **/
  
  public Boolean getALLDAY() {
    return ALL_DAY;
  }

  public void setALLDAY(Boolean ALL_DAY) {
    this.ALL_DAY = ALL_DAY;
  }

  public Activity DURATION(Integer DURATION) {
    this.DURATION = DURATION;
    return this;
  }

   /**
   * Get DURATION
   * @return DURATION
  **/
  
  public Integer getDURATION() {
    return DURATION;
  }

  public void setDURATION(Integer DURATION) {
    this.DURATION = DURATION;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activity apIActivity = (Activity) o;
    return Objects.equals(this.ACTIVITY_ID, apIActivity.ACTIVITY_ID) &&
        Objects.equals(this.ACTIVITYSET_ID, apIActivity.ACTIVITYSET_ID) &&
        Objects.equals(this.ACTIVITY_NAME, apIActivity.ACTIVITY_NAME) &&
        Objects.equals(this.ACTIVITY_DETAILS, apIActivity.ACTIVITY_DETAILS) &&
        Objects.equals(this.ACTIVITY_TYPE, apIActivity.ACTIVITY_TYPE) &&
        Objects.equals(this.CATEGORY_ID, apIActivity.CATEGORY_ID) &&
        Objects.equals(this.REMINDER, apIActivity.REMINDER) &&
        Objects.equals(this.REMINDER_DAYS_BEFORE_DUE, apIActivity.REMINDER_DAYS_BEFORE_DUE) &&
        Objects.equals(this.REMINDER_TIME, apIActivity.REMINDER_TIME) &&
        Objects.equals(this.PUBLICLY_VISIBLE, apIActivity.PUBLICLY_VISIBLE) &&
        Objects.equals(this.OWNER_VISIBLE, apIActivity.OWNER_VISIBLE) &&
        Objects.equals(this.OWNER_USER_ID, apIActivity.OWNER_USER_ID) &&
        Objects.equals(this.RESPONSIBLE_USER_ID, apIActivity.RESPONSIBLE_USER_ID) &&
        Objects.equals(this.ASSIGNED_TEAM_ID, apIActivity.ASSIGNED_TEAM_ID) &&
        Objects.equals(this.SKIP_SUN, apIActivity.SKIP_SUN) &&
        Objects.equals(this.SKIP_MON, apIActivity.SKIP_MON) &&
        Objects.equals(this.SKIP_TUE, apIActivity.SKIP_TUE) &&
        Objects.equals(this.SKIP_WED, apIActivity.SKIP_WED) &&
        Objects.equals(this.SKIP_THU, apIActivity.SKIP_THU) &&
        Objects.equals(this.SKIP_FRI, apIActivity.SKIP_FRI) &&
        Objects.equals(this.SKIP_SAT, apIActivity.SKIP_SAT) &&
        Objects.equals(this.DUE_DAYS_AFTER_START, apIActivity.DUE_DAYS_AFTER_START) &&
        Objects.equals(this.DUE_DAYS_BEFORE_END, apIActivity.DUE_DAYS_BEFORE_END) &&
        Objects.equals(this.EVENT_DAYS_AFTER_START, apIActivity.EVENT_DAYS_AFTER_START) &&
        Objects.equals(this.EVENT_DAYS_BEFORE_END, apIActivity.EVENT_DAYS_BEFORE_END) &&
        Objects.equals(this.EVENT_TIME, apIActivity.EVENT_TIME) &&
        Objects.equals(this.ALL_DAY, apIActivity.ALL_DAY) &&
        Objects.equals(this.DURATION, apIActivity.DURATION);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ACTIVITY_ID, ACTIVITYSET_ID, ACTIVITY_NAME, ACTIVITY_DETAILS, ACTIVITY_TYPE, CATEGORY_ID, REMINDER, REMINDER_DAYS_BEFORE_DUE, REMINDER_TIME, PUBLICLY_VISIBLE, OWNER_VISIBLE, OWNER_USER_ID, RESPONSIBLE_USER_ID, ASSIGNED_TEAM_ID, SKIP_SUN, SKIP_MON, SKIP_TUE, SKIP_WED, SKIP_THU, SKIP_FRI, SKIP_SAT, DUE_DAYS_AFTER_START, DUE_DAYS_BEFORE_END, EVENT_DAYS_AFTER_START, EVENT_DAYS_BEFORE_END, EVENT_TIME, ALL_DAY, DURATION);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activity {\n");
    
    sb.append("    ACTIVITY_ID: ").append(toIndentedString(ACTIVITY_ID)).append("\n");
    sb.append("    ACTIVITYSET_ID: ").append(toIndentedString(ACTIVITYSET_ID)).append("\n");
    sb.append("    ACTIVITY_NAME: ").append(toIndentedString(ACTIVITY_NAME)).append("\n");
    sb.append("    ACTIVITY_DETAILS: ").append(toIndentedString(ACTIVITY_DETAILS)).append("\n");
    sb.append("    ACTIVITY_TYPE: ").append(toIndentedString(ACTIVITY_TYPE)).append("\n");
    sb.append("    CATEGORY_ID: ").append(toIndentedString(CATEGORY_ID)).append("\n");
    sb.append("    REMINDER: ").append(toIndentedString(REMINDER)).append("\n");
    sb.append("    REMINDER_DAYS_BEFORE_DUE: ").append(toIndentedString(REMINDER_DAYS_BEFORE_DUE)).append("\n");
    sb.append("    REMINDER_TIME: ").append(toIndentedString(REMINDER_TIME)).append("\n");
    sb.append("    PUBLICLY_VISIBLE: ").append(toIndentedString(PUBLICLY_VISIBLE)).append("\n");
    sb.append("    OWNER_VISIBLE: ").append(toIndentedString(OWNER_VISIBLE)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    RESPONSIBLE_USER_ID: ").append(toIndentedString(RESPONSIBLE_USER_ID)).append("\n");
    sb.append("    ASSIGNED_TEAM_ID: ").append(toIndentedString(ASSIGNED_TEAM_ID)).append("\n");
    sb.append("    SKIP_SUN: ").append(toIndentedString(SKIP_SUN)).append("\n");
    sb.append("    SKIP_MON: ").append(toIndentedString(SKIP_MON)).append("\n");
    sb.append("    SKIP_TUE: ").append(toIndentedString(SKIP_TUE)).append("\n");
    sb.append("    SKIP_WED: ").append(toIndentedString(SKIP_WED)).append("\n");
    sb.append("    SKIP_THU: ").append(toIndentedString(SKIP_THU)).append("\n");
    sb.append("    SKIP_FRI: ").append(toIndentedString(SKIP_FRI)).append("\n");
    sb.append("    SKIP_SAT: ").append(toIndentedString(SKIP_SAT)).append("\n");
    sb.append("    DUE_DAYS_AFTER_START: ").append(toIndentedString(DUE_DAYS_AFTER_START)).append("\n");
    sb.append("    DUE_DAYS_BEFORE_END: ").append(toIndentedString(DUE_DAYS_BEFORE_END)).append("\n");
    sb.append("    EVENT_DAYS_AFTER_START: ").append(toIndentedString(EVENT_DAYS_AFTER_START)).append("\n");
    sb.append("    EVENT_DAYS_BEFORE_END: ").append(toIndentedString(EVENT_DAYS_BEFORE_END)).append("\n");
    sb.append("    EVENT_TIME: ").append(toIndentedString(EVENT_TIME)).append("\n");
    sb.append("    ALL_DAY: ").append(toIndentedString(ALL_DAY)).append("\n");
    sb.append("    DURATION: ").append(toIndentedString(DURATION)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

