/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.insightly.model.EventLink;


import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * CalendarEvent
 */
@JacksonXmlRootElement(localName = "CalendarEvent")
@XmlRootElement(name = "CalendarEvent")
@XmlAccessorType(XmlAccessType.FIELD)
public class CalendarEvent implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("EVENT_ID")
  @JacksonXmlProperty(localName = "EVENT_ID")
  @XmlElement(name = "EVENT_ID")
  private Long EVENT_ID = null;

  @JsonProperty("TITLE")
  @JacksonXmlProperty(localName = "TITLE")
  @XmlElement(name = "TITLE")
  private String TITLE = null;

  @JsonProperty("LOCATION")
  @JacksonXmlProperty(localName = "LOCATION")
  @XmlElement(name = "LOCATION")
  private String LOCATION = null;

  @JsonProperty("DETAILS")
  @JacksonXmlProperty(localName = "DETAILS")
  @XmlElement(name = "DETAILS")
  private String DETAILS = null;

  @JsonProperty("START_DATE_UTC")
  @JacksonXmlProperty(localName = "START_DATE_UTC")
  @XmlElement(name = "START_DATE_UTC")
  private OffsetDateTime START_DATE_UTC = null;

  @JsonProperty("END_DATE_UTC")
  @JacksonXmlProperty(localName = "END_DATE_UTC")
  @XmlElement(name = "END_DATE_UTC")
  private OffsetDateTime END_DATE_UTC = null;

  @JsonProperty("ALL_DAY")
  @JacksonXmlProperty(localName = "ALL_DAY")
  @XmlElement(name = "ALL_DAY")
  private Boolean ALL_DAY = null;

  @JsonProperty("PUBLICLY_VISIBLE")
  @JacksonXmlProperty(localName = "PUBLICLY_VISIBLE")
  @XmlElement(name = "PUBLICLY_VISIBLE")
  private Boolean PUBLICLY_VISIBLE = null;

  @JsonProperty("REMINDER_DATE_UTC")
  @JacksonXmlProperty(localName = "REMINDER_DATE_UTC")
  @XmlElement(name = "REMINDER_DATE_UTC")
  private OffsetDateTime REMINDER_DATE_UTC = null;

  @JsonProperty("REMINDER_SENT")
  @JacksonXmlProperty(localName = "REMINDER_SENT")
  @XmlElement(name = "REMINDER_SENT")
  private Boolean REMINDER_SENT = null;

  @JsonProperty("EVENTLINKS")
  @JacksonXmlProperty(localName = "EVENTLINKS")
  @XmlElement(name = "EVENTLINKS")
  private List<EventLink> EVENTLINKS = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public CalendarEvent EVENT_ID(Long EVENT_ID) {
    this.EVENT_ID = EVENT_ID;
    return this;
  }

   /**
   * Get EVENT_ID
   * @return EVENT_ID
  **/
  
  public Long getEVENTID() {
    return EVENT_ID;
  }

  public void setEVENTID(Long EVENT_ID) {
    this.EVENT_ID = EVENT_ID;
  }

  public CalendarEvent TITLE(String TITLE) {
    this.TITLE = TITLE;
    return this;
  }

   /**
   * Get TITLE
   * @return TITLE
  **/
  
  public String getTITLE() {
    return TITLE;
  }

  public void setTITLE(String TITLE) {
    this.TITLE = TITLE;
  }

  public CalendarEvent LOCATION(String LOCATION) {
    this.LOCATION = LOCATION;
    return this;
  }

   /**
   * Get LOCATION
   * @return LOCATION
  **/
  
  public String getLOCATION() {
    return LOCATION;
  }

  public void setLOCATION(String LOCATION) {
    this.LOCATION = LOCATION;
  }

  public CalendarEvent DETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
    return this;
  }

   /**
   * Get DETAILS
   * @return DETAILS
  **/
  
  public String getDETAILS() {
    return DETAILS;
  }

  public void setDETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
  }

  public CalendarEvent START_DATE_UTC(OffsetDateTime START_DATE_UTC) {
    this.START_DATE_UTC = START_DATE_UTC;
    return this;
  }

   /**
   * Get START_DATE_UTC
   * @return START_DATE_UTC
  **/
  
  public OffsetDateTime getSTARTDATEUTC() {
    return START_DATE_UTC;
  }

  public void setSTARTDATEUTC(OffsetDateTime START_DATE_UTC) {
    this.START_DATE_UTC = START_DATE_UTC;
  }

  public CalendarEvent END_DATE_UTC(OffsetDateTime END_DATE_UTC) {
    this.END_DATE_UTC = END_DATE_UTC;
    return this;
  }

   /**
   * Get END_DATE_UTC
   * @return END_DATE_UTC
  **/
  
  public OffsetDateTime getENDDATEUTC() {
    return END_DATE_UTC;
  }

  public void setENDDATEUTC(OffsetDateTime END_DATE_UTC) {
    this.END_DATE_UTC = END_DATE_UTC;
  }

  public CalendarEvent ALL_DAY(Boolean ALL_DAY) {
    this.ALL_DAY = ALL_DAY;
    return this;
  }

   /**
   * Get ALL_DAY
   * @return ALL_DAY
  **/
  
  public Boolean getALLDAY() {
    return ALL_DAY;
  }

  public void setALLDAY(Boolean ALL_DAY) {
    this.ALL_DAY = ALL_DAY;
  }

  public CalendarEvent PUBLICLY_VISIBLE(Boolean PUBLICLY_VISIBLE) {
    this.PUBLICLY_VISIBLE = PUBLICLY_VISIBLE;
    return this;
  }

   /**
   * Get PUBLICLY_VISIBLE
   * @return PUBLICLY_VISIBLE
  **/
  
  public Boolean getPUBLICLYVISIBLE() {
    return PUBLICLY_VISIBLE;
  }

  public void setPUBLICLYVISIBLE(Boolean PUBLICLY_VISIBLE) {
    this.PUBLICLY_VISIBLE = PUBLICLY_VISIBLE;
  }

  public CalendarEvent REMINDER_DATE_UTC(OffsetDateTime REMINDER_DATE_UTC) {
    this.REMINDER_DATE_UTC = REMINDER_DATE_UTC;
    return this;
  }

   /**
   * Get REMINDER_DATE_UTC
   * @return REMINDER_DATE_UTC
  **/
  
  public OffsetDateTime getREMINDERDATEUTC() {
    return REMINDER_DATE_UTC;
  }

  public void setREMINDERDATEUTC(OffsetDateTime REMINDER_DATE_UTC) {
    this.REMINDER_DATE_UTC = REMINDER_DATE_UTC;
  }

  public CalendarEvent REMINDER_SENT(Boolean REMINDER_SENT) {
    this.REMINDER_SENT = REMINDER_SENT;
    return this;
  }

   /**
   * Get REMINDER_SENT
   * @return REMINDER_SENT
  **/
  
  public Boolean getREMINDERSENT() {
    return REMINDER_SENT;
  }

  public void setREMINDERSENT(Boolean REMINDER_SENT) {
    this.REMINDER_SENT = REMINDER_SENT;
  }

  public CalendarEvent EVENTLINKS(List<EventLink> EVENTLINKS) {
    this.EVENTLINKS = EVENTLINKS;
    return this;
  }

  public CalendarEvent addEVENTLINKSItem(EventLink EVENTLINKSItem) {
    if (this.EVENTLINKS == null) {
      this.EVENTLINKS = new ArrayList<EventLink>();
    }
    this.EVENTLINKS.add(EVENTLINKSItem);
    return this;
  }

   /**
   * Get EVENTLINKS
   * @return EVENTLINKS
  **/
  
  public List<EventLink> getEVENTLINKS() {
    return EVENTLINKS;
  }

  public void setEVENTLINKS(List<EventLink> EVENTLINKS) {
    this.EVENTLINKS = EVENTLINKS;
  }

  public CalendarEvent OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public CalendarEvent DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public CalendarEvent DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public CalendarEvent CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public CalendarEvent CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalendarEvent calendarEvent = (CalendarEvent) o;
    return Objects.equals(this.EVENT_ID, calendarEvent.EVENT_ID) &&
        Objects.equals(this.TITLE, calendarEvent.TITLE) &&
        Objects.equals(this.LOCATION, calendarEvent.LOCATION) &&
        Objects.equals(this.DETAILS, calendarEvent.DETAILS) &&
        Objects.equals(this.START_DATE_UTC, calendarEvent.START_DATE_UTC) &&
        Objects.equals(this.END_DATE_UTC, calendarEvent.END_DATE_UTC) &&
        Objects.equals(this.ALL_DAY, calendarEvent.ALL_DAY) &&
        Objects.equals(this.PUBLICLY_VISIBLE, calendarEvent.PUBLICLY_VISIBLE) &&
        Objects.equals(this.REMINDER_DATE_UTC, calendarEvent.REMINDER_DATE_UTC) &&
        Objects.equals(this.REMINDER_SENT, calendarEvent.REMINDER_SENT) &&
        Objects.equals(this.EVENTLINKS, calendarEvent.EVENTLINKS) &&
        Objects.equals(this.OWNER_USER_ID, calendarEvent.OWNER_USER_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, calendarEvent.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, calendarEvent.DATE_UPDATED_UTC) &&
        Objects.equals(this.CAN_EDIT, calendarEvent.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, calendarEvent.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EVENT_ID, TITLE, LOCATION, DETAILS, START_DATE_UTC, END_DATE_UTC, ALL_DAY, PUBLICLY_VISIBLE, REMINDER_DATE_UTC, REMINDER_SENT, EVENTLINKS, OWNER_USER_ID, DATE_CREATED_UTC, DATE_UPDATED_UTC, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalendarEvent {\n");
    
    sb.append("    EVENT_ID: ").append(toIndentedString(EVENT_ID)).append("\n");
    sb.append("    TITLE: ").append(toIndentedString(TITLE)).append("\n");
    sb.append("    LOCATION: ").append(toIndentedString(LOCATION)).append("\n");
    sb.append("    DETAILS: ").append(toIndentedString(DETAILS)).append("\n");
    sb.append("    START_DATE_UTC: ").append(toIndentedString(START_DATE_UTC)).append("\n");
    sb.append("    END_DATE_UTC: ").append(toIndentedString(END_DATE_UTC)).append("\n");
    sb.append("    ALL_DAY: ").append(toIndentedString(ALL_DAY)).append("\n");
    sb.append("    PUBLICLY_VISIBLE: ").append(toIndentedString(PUBLICLY_VISIBLE)).append("\n");
    sb.append("    REMINDER_DATE_UTC: ").append(toIndentedString(REMINDER_DATE_UTC)).append("\n");
    sb.append("    REMINDER_SENT: ").append(toIndentedString(REMINDER_SENT)).append("\n");
    sb.append("    EVENTLINKS: ").append(toIndentedString(EVENTLINKS)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

