/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Comment
 */
@JacksonXmlRootElement(localName = "Comment")
@XmlRootElement(name = "Comment")
@XmlAccessorType(XmlAccessType.FIELD)
public class Comment implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("COMMENT_ID")
  @JacksonXmlProperty(localName = "COMMENT_ID")
  @XmlElement(name = "COMMENT_ID")
  private Long COMMENT_ID = null;

  @JsonProperty("BODY")
  @JacksonXmlProperty(localName = "BODY")
  @XmlElement(name = "BODY")
  private String BODY = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("NOTE_ID")
  @JacksonXmlProperty(localName = "NOTE_ID")
  @XmlElement(name = "NOTE_ID")
  private Long NOTE_ID = null;

  @JsonProperty("EMAIL_ID")
  @JacksonXmlProperty(localName = "EMAIL_ID")
  @XmlElement(name = "EMAIL_ID")
  private Long EMAIL_ID = null;

  @JsonProperty("TASK_ID")
  @JacksonXmlProperty(localName = "TASK_ID")
  @XmlElement(name = "TASK_ID")
  private Long TASK_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public Comment COMMENT_ID(Long COMMENT_ID) {
    this.COMMENT_ID = COMMENT_ID;
    return this;
  }

   /**
   * Get COMMENT_ID
   * @return COMMENT_ID
  **/
  
  public Long getCOMMENTID() {
    return COMMENT_ID;
  }

  public void setCOMMENTID(Long COMMENT_ID) {
    this.COMMENT_ID = COMMENT_ID;
  }

  public Comment BODY(String BODY) {
    this.BODY = BODY;
    return this;
  }

   /**
   * Get BODY
   * @return BODY
  **/
  
  public String getBODY() {
    return BODY;
  }

  public void setBODY(String BODY) {
    this.BODY = BODY;
  }

  public Comment OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public Comment NOTE_ID(Long NOTE_ID) {
    this.NOTE_ID = NOTE_ID;
    return this;
  }

   /**
   * Get NOTE_ID
   * @return NOTE_ID
  **/
  
  public Long getNOTEID() {
    return NOTE_ID;
  }

  public void setNOTEID(Long NOTE_ID) {
    this.NOTE_ID = NOTE_ID;
  }

  public Comment EMAIL_ID(Long EMAIL_ID) {
    this.EMAIL_ID = EMAIL_ID;
    return this;
  }

   /**
   * Get EMAIL_ID
   * @return EMAIL_ID
  **/
  
  public Long getEMAILID() {
    return EMAIL_ID;
  }

  public void setEMAILID(Long EMAIL_ID) {
    this.EMAIL_ID = EMAIL_ID;
  }

  public Comment TASK_ID(Long TASK_ID) {
    this.TASK_ID = TASK_ID;
    return this;
  }

   /**
   * Get TASK_ID
   * @return TASK_ID
  **/
  
  public Long getTASKID() {
    return TASK_ID;
  }

  public void setTASKID(Long TASK_ID) {
    this.TASK_ID = TASK_ID;
  }

  public Comment DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public Comment DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public Comment CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public Comment CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Comment comment = (Comment) o;
    return Objects.equals(this.COMMENT_ID, comment.COMMENT_ID) &&
        Objects.equals(this.BODY, comment.BODY) &&
        Objects.equals(this.OWNER_USER_ID, comment.OWNER_USER_ID) &&
        Objects.equals(this.NOTE_ID, comment.NOTE_ID) &&
        Objects.equals(this.EMAIL_ID, comment.EMAIL_ID) &&
        Objects.equals(this.TASK_ID, comment.TASK_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, comment.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, comment.DATE_UPDATED_UTC) &&
        Objects.equals(this.CAN_EDIT, comment.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, comment.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(COMMENT_ID, BODY, OWNER_USER_ID, NOTE_ID, EMAIL_ID, TASK_ID, DATE_CREATED_UTC, DATE_UPDATED_UTC, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Comment {\n");
    
    sb.append("    COMMENT_ID: ").append(toIndentedString(COMMENT_ID)).append("\n");
    sb.append("    BODY: ").append(toIndentedString(BODY)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    NOTE_ID: ").append(toIndentedString(NOTE_ID)).append("\n");
    sb.append("    EMAIL_ID: ").append(toIndentedString(EMAIL_ID)).append("\n");
    sb.append("    TASK_ID: ").append(toIndentedString(TASK_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

