/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * ContactLink
 */
@JacksonXmlRootElement(localName = "ContactLink")
@XmlRootElement(name = "ContactLink")
@XmlAccessorType(XmlAccessType.FIELD)
public class ContactLink implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("CONTACT_LINK_ID")
  @JacksonXmlProperty(localName = "CONTACT_LINK_ID")
  @XmlElement(name = "CONTACT_LINK_ID")
  private Long CONTACT_LINK_ID = null;

  @JsonProperty("FIRST_CONTACT_ID")
  @JacksonXmlProperty(localName = "FIRST_CONTACT_ID")
  @XmlElement(name = "FIRST_CONTACT_ID")
  private Long FIRST_CONTACT_ID = null;

  @JsonProperty("SECOND_CONTACT_ID")
  @JacksonXmlProperty(localName = "SECOND_CONTACT_ID")
  @XmlElement(name = "SECOND_CONTACT_ID")
  private Long SECOND_CONTACT_ID = null;

  @JsonProperty("RELATIONSHIP_ID")
  @JacksonXmlProperty(localName = "RELATIONSHIP_ID")
  @XmlElement(name = "RELATIONSHIP_ID")
  private Long RELATIONSHIP_ID = null;

  @JsonProperty("DETAILS")
  @JacksonXmlProperty(localName = "DETAILS")
  @XmlElement(name = "DETAILS")
  private String DETAILS = null;

  public ContactLink CONTACT_LINK_ID(Long CONTACT_LINK_ID) {
    this.CONTACT_LINK_ID = CONTACT_LINK_ID;
    return this;
  }

   /**
   * Get CONTACT_LINK_ID
   * @return CONTACT_LINK_ID
  **/
  
  public Long getCONTACTLINKID() {
    return CONTACT_LINK_ID;
  }

  public void setCONTACTLINKID(Long CONTACT_LINK_ID) {
    this.CONTACT_LINK_ID = CONTACT_LINK_ID;
  }

  public ContactLink FIRST_CONTACT_ID(Long FIRST_CONTACT_ID) {
    this.FIRST_CONTACT_ID = FIRST_CONTACT_ID;
    return this;
  }

   /**
   * Get FIRST_CONTACT_ID
   * @return FIRST_CONTACT_ID
  **/
  
  public Long getFIRSTCONTACTID() {
    return FIRST_CONTACT_ID;
  }

  public void setFIRSTCONTACTID(Long FIRST_CONTACT_ID) {
    this.FIRST_CONTACT_ID = FIRST_CONTACT_ID;
  }

  public ContactLink SECOND_CONTACT_ID(Long SECOND_CONTACT_ID) {
    this.SECOND_CONTACT_ID = SECOND_CONTACT_ID;
    return this;
  }

   /**
   * Get SECOND_CONTACT_ID
   * @return SECOND_CONTACT_ID
  **/
  
  public Long getSECONDCONTACTID() {
    return SECOND_CONTACT_ID;
  }

  public void setSECONDCONTACTID(Long SECOND_CONTACT_ID) {
    this.SECOND_CONTACT_ID = SECOND_CONTACT_ID;
  }

  public ContactLink RELATIONSHIP_ID(Long RELATIONSHIP_ID) {
    this.RELATIONSHIP_ID = RELATIONSHIP_ID;
    return this;
  }

   /**
   * Get RELATIONSHIP_ID
   * @return RELATIONSHIP_ID
  **/
  
  public Long getRELATIONSHIPID() {
    return RELATIONSHIP_ID;
  }

  public void setRELATIONSHIPID(Long RELATIONSHIP_ID) {
    this.RELATIONSHIP_ID = RELATIONSHIP_ID;
  }

  public ContactLink DETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
    return this;
  }

   /**
   * Get DETAILS
   * @return DETAILS
  **/
  
  public String getDETAILS() {
    return DETAILS;
  }

  public void setDETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactLink contactLink = (ContactLink) o;
    return Objects.equals(this.CONTACT_LINK_ID, contactLink.CONTACT_LINK_ID) &&
        Objects.equals(this.FIRST_CONTACT_ID, contactLink.FIRST_CONTACT_ID) &&
        Objects.equals(this.SECOND_CONTACT_ID, contactLink.SECOND_CONTACT_ID) &&
        Objects.equals(this.RELATIONSHIP_ID, contactLink.RELATIONSHIP_ID) &&
        Objects.equals(this.DETAILS, contactLink.DETAILS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CONTACT_LINK_ID, FIRST_CONTACT_ID, SECOND_CONTACT_ID, RELATIONSHIP_ID, DETAILS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactLink {\n");
    
    sb.append("    CONTACT_LINK_ID: ").append(toIndentedString(CONTACT_LINK_ID)).append("\n");
    sb.append("    FIRST_CONTACT_ID: ").append(toIndentedString(FIRST_CONTACT_ID)).append("\n");
    sb.append("    SECOND_CONTACT_ID: ").append(toIndentedString(SECOND_CONTACT_ID)).append("\n");
    sb.append("    RELATIONSHIP_ID: ").append(toIndentedString(RELATIONSHIP_ID)).append("\n");
    sb.append("    DETAILS: ").append(toIndentedString(DETAILS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

