/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Country
 */
@JacksonXmlRootElement(localName = "Country")
@XmlRootElement(name = "Country")
@XmlAccessorType(XmlAccessType.FIELD)
public class Country implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("COUNTRY_NAME")
  @JacksonXmlProperty(localName = "COUNTRY_NAME")
  @XmlElement(name = "COUNTRY_NAME")
  private String COUNTRY_NAME = null;

  public Country COUNTRY_NAME(String COUNTRY_NAME) {
    this.COUNTRY_NAME = COUNTRY_NAME;
    return this;
  }

   /**
   * Get COUNTRY_NAME
   * @return COUNTRY_NAME
  **/
  
  public String getCOUNTRYNAME() {
    return COUNTRY_NAME;
  }

  public void setCOUNTRYNAME(String COUNTRY_NAME) {
    this.COUNTRY_NAME = COUNTRY_NAME;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Country apICountry = (Country) o;
    return Objects.equals(this.COUNTRY_NAME, apICountry.COUNTRY_NAME);
  }

  @Override
  public int hashCode() {
    return Objects.hash(COUNTRY_NAME);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Country {\n");
    
    sb.append("    COUNTRY_NAME: ").append(toIndentedString(COUNTRY_NAME)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

