/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Currency
 */
@JacksonXmlRootElement(localName = "Currency")
@XmlRootElement(name = "Currency")
@XmlAccessorType(XmlAccessType.FIELD)
public class Currency implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("CURRENCY_CODE")
  @JacksonXmlProperty(localName = "CURRENCY_CODE")
  @XmlElement(name = "CURRENCY_CODE")
  private String CURRENCY_CODE = null;

  @JsonProperty("CURRENCY_SYMBOL")
  @JacksonXmlProperty(localName = "CURRENCY_SYMBOL")
  @XmlElement(name = "CURRENCY_SYMBOL")
  private String CURRENCY_SYMBOL = null;

  public Currency CURRENCY_CODE(String CURRENCY_CODE) {
    this.CURRENCY_CODE = CURRENCY_CODE;
    return this;
  }

   /**
   * Get CURRENCY_CODE
   * @return CURRENCY_CODE
  **/
  
  public String getCURRENCYCODE() {
    return CURRENCY_CODE;
  }

  public void setCURRENCYCODE(String CURRENCY_CODE) {
    this.CURRENCY_CODE = CURRENCY_CODE;
  }

  public Currency CURRENCY_SYMBOL(String CURRENCY_SYMBOL) {
    this.CURRENCY_SYMBOL = CURRENCY_SYMBOL;
    return this;
  }

   /**
   * Get CURRENCY_SYMBOL
   * @return CURRENCY_SYMBOL
  **/
  
  public String getCURRENCYSYMBOL() {
    return CURRENCY_SYMBOL;
  }

  public void setCURRENCYSYMBOL(String CURRENCY_SYMBOL) {
    this.CURRENCY_SYMBOL = CURRENCY_SYMBOL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Currency apICurrency = (Currency) o;
    return Objects.equals(this.CURRENCY_CODE, apICurrency.CURRENCY_CODE) &&
        Objects.equals(this.CURRENCY_SYMBOL, apICurrency.CURRENCY_SYMBOL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CURRENCY_CODE, CURRENCY_SYMBOL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Currency {\n");
    
    sb.append("    CURRENCY_CODE: ").append(toIndentedString(CURRENCY_CODE)).append("\n");
    sb.append("    CURRENCY_SYMBOL: ").append(toIndentedString(CURRENCY_SYMBOL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

