/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.insightly.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.ToString;

/**
 * CustomFieldMetadata
 */
@JacksonXmlRootElement(localName = "CustomFieldMetadata")
@XmlRootElement(name = "CustomFieldMetadata")
@XmlAccessorType(XmlAccessType.FIELD)
@JsonAutoDetect(fieldVisibility = Visibility.ANY)
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
@Data
@EqualsAndHashCode(of = {"id", "fieldID", "fieldFor", "fieldLabel"})
@ToString(includeFieldNames =false,
	of = { "id", "fieldID", "fieldFor", "fieldLabel" })
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "CUSTOM_FIELD_METADATA")
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class)
public class CustomFieldMetadata implements Serializable {
	private static final long serialVersionUID = -3461971489913884187L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID")
	private Long id;
	
	@JsonProperty("CUSTOM_FIELD_ID")
	@JacksonXmlProperty(localName = "CUSTOM_FIELD_ID")
	@XmlElement(name = "CUSTOM_FIELD_ID")
	@Column(name = "FIELD_ID", unique=true, nullable = false)
	@NonNull
	private String fieldID = null;

	@JsonProperty("ORDER_ID")
	@JacksonXmlProperty(localName = "ORDER_ID")
	@XmlElement(name = "ORDER_ID")
	@Column(name = "ORDER_ID", unique=false, nullable = false)
	@NonNull
	private Long orderID = null;

	@JsonProperty("FIELD_FOR")
	@JacksonXmlProperty(localName = "FIELD_FOR")
	@XmlElement(name = "FIELD_FOR")
	@Column(name = "FIELD_FOR", unique=false, nullable = false)
	@NonNull
	private String fieldFor = null;

	@JsonProperty("FIELD_NAME")
	@JacksonXmlProperty(localName = "FIELD_NAME")
	@XmlElement(name = "FIELD_NAME")
	@Column(name = "FIELD_NAME", unique=false, nullable = false)
	@NonNull
	private String fieldLabel = null;

	@JsonProperty("FIELD_TYPE")
	@JacksonXmlProperty(localName = "FIELD_TYPE")
	@XmlElement(name = "FIELD_TYPE")
	@Column(name = "FIELD_TYPE", unique=false, nullable = false)
	@NonNull
	private String fieldType = null;

	@JsonProperty("FIELD_HELP_TEXT")
	@JacksonXmlProperty(localName = "FIELD_HELP_TEXT")
	@XmlElement(name = "FIELD_HELP_TEXT")
	@Column(name = "FIELD_HELP_TEXT", unique=false, nullable = true)
	private String fieldHelpText = null;

	@JsonProperty("DEFAULT_VALUE")
	@JacksonXmlProperty(localName = "DEFAULT_VALUE")
	@XmlElement(name = "DEFAULT_VALUE")
	@Column(name = "DEFAULT_VALUE", unique=false, nullable = true)
	private String defaultValue = null;

	@JsonProperty("GROUP_ID")
	@JacksonXmlProperty(localName = "GROUP_ID")
	@XmlElement(name = "GROUP_ID")
	@Column(name = "GROUP_ID", unique=false, nullable = true)
	private Long groupID = null;

	@JsonProperty("EDITABLE")
	@JacksonXmlProperty(localName = "EDITABLE")
	@XmlElement(name = "EDITABLE")
	@Column(name = "EDITABLE", unique=false, nullable = true)
	private Boolean editable = null;

	@JsonProperty("VISIBLE")
	@JacksonXmlProperty(localName = "VISIBLE")
	@XmlElement(name = "VISIBLE")
	@Column(name = "VISIBLE", unique=false, nullable = true)
	private Boolean visible = null;

	@JsonProperty("CUSTOM_FIELD_OPTIONS")
	@JsonManagedReference
	@JacksonXmlProperty(localName = "CUSTOM_FIELD_OPTIONS")
	@XmlElement(name = "CUSTOM_FIELD_OPTIONS")
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "customFieldMetadata")
	private List<CustomFieldOption> customFieldOptions = new ArrayList<CustomFieldOption>(0);
}
