/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.insightly.model.EmailLink;
import com.insightly.model.Tag;


import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Email
 */
@JacksonXmlRootElement(localName = "Email")
@XmlRootElement(name = "Email")
@XmlAccessorType(XmlAccessType.FIELD)
public class Email implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("EMAIL_ID")
  @JacksonXmlProperty(localName = "EMAIL_ID")
  @XmlElement(name = "EMAIL_ID")
  private Long EMAIL_ID = null;

  @JsonProperty("GMAIL_MESSAGE_ID")
  @JacksonXmlProperty(localName = "GMAIL_MESSAGE_ID")
  @XmlElement(name = "GMAIL_MESSAGE_ID")
  private String GMAIL_MESSAGE_ID = null;

  @JsonProperty("EMAIL_DATE_UTC")
  @JacksonXmlProperty(localName = "EMAIL_DATE_UTC")
  @XmlElement(name = "EMAIL_DATE_UTC")
  private OffsetDateTime EMAIL_DATE_UTC = null;

  @JsonProperty("EMAIL_FROM")
  @JacksonXmlProperty(localName = "EMAIL_FROM")
  @XmlElement(name = "EMAIL_FROM")
  private String EMAIL_FROM = null;

  @JsonProperty("EMAIL_TO")
  @JacksonXmlProperty(localName = "EMAIL_TO")
  @XmlElement(name = "EMAIL_TO")
  private String EMAIL_TO = null;

  @JsonProperty("EMAIL_CC")
  @JacksonXmlProperty(localName = "EMAIL_CC")
  @XmlElement(name = "EMAIL_CC")
  private String EMAIL_CC = null;

  @JsonProperty("SUBJECT")
  @JacksonXmlProperty(localName = "SUBJECT")
  @XmlElement(name = "SUBJECT")
  private String SUBJECT = null;

  @JsonProperty("BODY")
  @JacksonXmlProperty(localName = "BODY")
  @XmlElement(name = "BODY")
  private String BODY = null;

  @JsonProperty("BODY_EXTRACT")
  @JacksonXmlProperty(localName = "BODY_EXTRACT")
  @XmlElement(name = "BODY_EXTRACT")
  private String BODY_EXTRACT = null;

  @JsonProperty("FORMAT")
  @JacksonXmlProperty(localName = "FORMAT")
  @XmlElement(name = "FORMAT")
  private String FORMAT = null;

  @JsonProperty("SIZE")
  @JacksonXmlProperty(localName = "SIZE")
  @XmlElement(name = "SIZE")
  private Long SIZE = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("VISIBLE_TO")
  @JacksonXmlProperty(localName = "VISIBLE_TO")
  @XmlElement(name = "VISIBLE_TO")
  private String VISIBLE_TO = null;

  @JsonProperty("VISIBLE_TEAM_ID")
  @JacksonXmlProperty(localName = "VISIBLE_TEAM_ID")
  @XmlElement(name = "VISIBLE_TEAM_ID")
  private Long VISIBLE_TEAM_ID = null;

  @JsonProperty("VISIBLE_USER_IDS")
  @JacksonXmlProperty(localName = "VISIBLE_USER_IDS")
  @XmlElement(name = "VISIBLE_USER_IDS")
  private String VISIBLE_USER_IDS = null;

  @JsonProperty("EMAILLINKS")
  @JacksonXmlProperty(localName = "EMAILLINKS")
  @XmlElement(name = "EMAILLINKS")
  private List<EmailLink> EMAILLINKS = null;

  @JsonProperty("TAGS")
  @JacksonXmlProperty(localName = "TAGS")
  @XmlElement(name = "TAGS")
  private List<Tag> TAGS = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public Email EMAIL_ID(Long EMAIL_ID) {
    this.EMAIL_ID = EMAIL_ID;
    return this;
  }

   /**
   * Get EMAIL_ID
   * @return EMAIL_ID
  **/
  
  public Long getEMAILID() {
    return EMAIL_ID;
  }

  public void setEMAILID(Long EMAIL_ID) {
    this.EMAIL_ID = EMAIL_ID;
  }

  public Email GMAIL_MESSAGE_ID(String GMAIL_MESSAGE_ID) {
    this.GMAIL_MESSAGE_ID = GMAIL_MESSAGE_ID;
    return this;
  }

   /**
   * Get GMAIL_MESSAGE_ID
   * @return GMAIL_MESSAGE_ID
  **/
  
  public String getGMAILMESSAGEID() {
    return GMAIL_MESSAGE_ID;
  }

  public void setGMAILMESSAGEID(String GMAIL_MESSAGE_ID) {
    this.GMAIL_MESSAGE_ID = GMAIL_MESSAGE_ID;
  }

  public Email EMAIL_DATE_UTC(OffsetDateTime EMAIL_DATE_UTC) {
    this.EMAIL_DATE_UTC = EMAIL_DATE_UTC;
    return this;
  }

   /**
   * Get EMAIL_DATE_UTC
   * @return EMAIL_DATE_UTC
  **/
  
  public OffsetDateTime getEMAILDATEUTC() {
    return EMAIL_DATE_UTC;
  }

  public void setEMAILDATEUTC(OffsetDateTime EMAIL_DATE_UTC) {
    this.EMAIL_DATE_UTC = EMAIL_DATE_UTC;
  }

  public Email EMAIL_FROM(String EMAIL_FROM) {
    this.EMAIL_FROM = EMAIL_FROM;
    return this;
  }

   /**
   * Get EMAIL_FROM
   * @return EMAIL_FROM
  **/
  
  public String getEMAILFROM() {
    return EMAIL_FROM;
  }

  public void setEMAILFROM(String EMAIL_FROM) {
    this.EMAIL_FROM = EMAIL_FROM;
  }

  public Email EMAIL_TO(String EMAIL_TO) {
    this.EMAIL_TO = EMAIL_TO;
    return this;
  }

   /**
   * Get EMAIL_TO
   * @return EMAIL_TO
  **/
  
  public String getEMAILTO() {
    return EMAIL_TO;
  }

  public void setEMAILTO(String EMAIL_TO) {
    this.EMAIL_TO = EMAIL_TO;
  }

  public Email EMAIL_CC(String EMAIL_CC) {
    this.EMAIL_CC = EMAIL_CC;
    return this;
  }

   /**
   * Get EMAIL_CC
   * @return EMAIL_CC
  **/
  
  public String getEMAILCC() {
    return EMAIL_CC;
  }

  public void setEMAILCC(String EMAIL_CC) {
    this.EMAIL_CC = EMAIL_CC;
  }

  public Email SUBJECT(String SUBJECT) {
    this.SUBJECT = SUBJECT;
    return this;
  }

   /**
   * Get SUBJECT
   * @return SUBJECT
  **/
  
  public String getSUBJECT() {
    return SUBJECT;
  }

  public void setSUBJECT(String SUBJECT) {
    this.SUBJECT = SUBJECT;
  }

  public Email BODY(String BODY) {
    this.BODY = BODY;
    return this;
  }

   /**
   * Get BODY
   * @return BODY
  **/
  
  public String getBODY() {
    return BODY;
  }

  public void setBODY(String BODY) {
    this.BODY = BODY;
  }

  public Email BODY_EXTRACT(String BODY_EXTRACT) {
    this.BODY_EXTRACT = BODY_EXTRACT;
    return this;
  }

   /**
   * Get BODY_EXTRACT
   * @return BODY_EXTRACT
  **/
  
  public String getBODYEXTRACT() {
    return BODY_EXTRACT;
  }

  public void setBODYEXTRACT(String BODY_EXTRACT) {
    this.BODY_EXTRACT = BODY_EXTRACT;
  }

  public Email FORMAT(String FORMAT) {
    this.FORMAT = FORMAT;
    return this;
  }

   /**
   * Get FORMAT
   * @return FORMAT
  **/
  
  public String getFORMAT() {
    return FORMAT;
  }

  public void setFORMAT(String FORMAT) {
    this.FORMAT = FORMAT;
  }

  public Email SIZE(Long SIZE) {
    this.SIZE = SIZE;
    return this;
  }

   /**
   * Get SIZE
   * @return SIZE
  **/
  
  public Long getSIZE() {
    return SIZE;
  }

  public void setSIZE(Long SIZE) {
    this.SIZE = SIZE;
  }

  public Email OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public Email DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public Email VISIBLE_TO(String VISIBLE_TO) {
    this.VISIBLE_TO = VISIBLE_TO;
    return this;
  }

   /**
   * Get VISIBLE_TO
   * @return VISIBLE_TO
  **/
  
  public String getVISIBLETO() {
    return VISIBLE_TO;
  }

  public void setVISIBLETO(String VISIBLE_TO) {
    this.VISIBLE_TO = VISIBLE_TO;
  }

  public Email VISIBLE_TEAM_ID(Long VISIBLE_TEAM_ID) {
    this.VISIBLE_TEAM_ID = VISIBLE_TEAM_ID;
    return this;
  }

   /**
   * Get VISIBLE_TEAM_ID
   * @return VISIBLE_TEAM_ID
  **/
  
  public Long getVISIBLETEAMID() {
    return VISIBLE_TEAM_ID;
  }

  public void setVISIBLETEAMID(Long VISIBLE_TEAM_ID) {
    this.VISIBLE_TEAM_ID = VISIBLE_TEAM_ID;
  }

  public Email VISIBLE_USER_IDS(String VISIBLE_USER_IDS) {
    this.VISIBLE_USER_IDS = VISIBLE_USER_IDS;
    return this;
  }

   /**
   * Get VISIBLE_USER_IDS
   * @return VISIBLE_USER_IDS
  **/
  
  public String getVISIBLEUSERIDS() {
    return VISIBLE_USER_IDS;
  }

  public void setVISIBLEUSERIDS(String VISIBLE_USER_IDS) {
    this.VISIBLE_USER_IDS = VISIBLE_USER_IDS;
  }

  public Email EMAILLINKS(List<EmailLink> EMAILLINKS) {
    this.EMAILLINKS = EMAILLINKS;
    return this;
  }

  public Email addEMAILLINKSItem(EmailLink EMAILLINKSItem) {
    if (this.EMAILLINKS == null) {
      this.EMAILLINKS = new ArrayList<EmailLink>();
    }
    this.EMAILLINKS.add(EMAILLINKSItem);
    return this;
  }

   /**
   * Get EMAILLINKS
   * @return EMAILLINKS
  **/
  
  public List<EmailLink> getEMAILLINKS() {
    return EMAILLINKS;
  }

  public void setEMAILLINKS(List<EmailLink> EMAILLINKS) {
    this.EMAILLINKS = EMAILLINKS;
  }

  public Email TAGS(List<Tag> TAGS) {
    this.TAGS = TAGS;
    return this;
  }

  public Email addTAGSItem(Tag TAGSItem) {
    if (this.TAGS == null) {
      this.TAGS = new ArrayList<Tag>();
    }
    this.TAGS.add(TAGSItem);
    return this;
  }

   /**
   * Get TAGS
   * @return TAGS
  **/
  
  public List<Tag> getTAGS() {
    return TAGS;
  }

  public void setTAGS(List<Tag> TAGS) {
    this.TAGS = TAGS;
  }

  public Email CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public Email CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Email email = (Email) o;
    return Objects.equals(this.EMAIL_ID, email.EMAIL_ID) &&
        Objects.equals(this.GMAIL_MESSAGE_ID, email.GMAIL_MESSAGE_ID) &&
        Objects.equals(this.EMAIL_DATE_UTC, email.EMAIL_DATE_UTC) &&
        Objects.equals(this.EMAIL_FROM, email.EMAIL_FROM) &&
        Objects.equals(this.EMAIL_TO, email.EMAIL_TO) &&
        Objects.equals(this.EMAIL_CC, email.EMAIL_CC) &&
        Objects.equals(this.SUBJECT, email.SUBJECT) &&
        Objects.equals(this.BODY, email.BODY) &&
        Objects.equals(this.BODY_EXTRACT, email.BODY_EXTRACT) &&
        Objects.equals(this.FORMAT, email.FORMAT) &&
        Objects.equals(this.SIZE, email.SIZE) &&
        Objects.equals(this.OWNER_USER_ID, email.OWNER_USER_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, email.DATE_CREATED_UTC) &&
        Objects.equals(this.VISIBLE_TO, email.VISIBLE_TO) &&
        Objects.equals(this.VISIBLE_TEAM_ID, email.VISIBLE_TEAM_ID) &&
        Objects.equals(this.VISIBLE_USER_IDS, email.VISIBLE_USER_IDS) &&
        Objects.equals(this.EMAILLINKS, email.EMAILLINKS) &&
        Objects.equals(this.TAGS, email.TAGS) &&
        Objects.equals(this.CAN_EDIT, email.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, email.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EMAIL_ID, GMAIL_MESSAGE_ID, EMAIL_DATE_UTC, EMAIL_FROM, EMAIL_TO, EMAIL_CC, SUBJECT, BODY, BODY_EXTRACT, FORMAT, SIZE, OWNER_USER_ID, DATE_CREATED_UTC, VISIBLE_TO, VISIBLE_TEAM_ID, VISIBLE_USER_IDS, EMAILLINKS, TAGS, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Email {\n");
    
    sb.append("    EMAIL_ID: ").append(toIndentedString(EMAIL_ID)).append("\n");
    sb.append("    GMAIL_MESSAGE_ID: ").append(toIndentedString(GMAIL_MESSAGE_ID)).append("\n");
    sb.append("    EMAIL_DATE_UTC: ").append(toIndentedString(EMAIL_DATE_UTC)).append("\n");
    sb.append("    EMAIL_FROM: ").append(toIndentedString(EMAIL_FROM)).append("\n");
    sb.append("    EMAIL_TO: ").append(toIndentedString(EMAIL_TO)).append("\n");
    sb.append("    EMAIL_CC: ").append(toIndentedString(EMAIL_CC)).append("\n");
    sb.append("    SUBJECT: ").append(toIndentedString(SUBJECT)).append("\n");
    sb.append("    BODY: ").append(toIndentedString(BODY)).append("\n");
    sb.append("    BODY_EXTRACT: ").append(toIndentedString(BODY_EXTRACT)).append("\n");
    sb.append("    FORMAT: ").append(toIndentedString(FORMAT)).append("\n");
    sb.append("    SIZE: ").append(toIndentedString(SIZE)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    VISIBLE_TO: ").append(toIndentedString(VISIBLE_TO)).append("\n");
    sb.append("    VISIBLE_TEAM_ID: ").append(toIndentedString(VISIBLE_TEAM_ID)).append("\n");
    sb.append("    VISIBLE_USER_IDS: ").append(toIndentedString(VISIBLE_USER_IDS)).append("\n");
    sb.append("    EMAILLINKS: ").append(toIndentedString(EMAILLINKS)).append("\n");
    sb.append("    TAGS: ").append(toIndentedString(TAGS)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

