/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * EventLink
 */
@JacksonXmlRootElement(localName = "EventLink")
@XmlRootElement(name = "EventLink")
@XmlAccessorType(XmlAccessType.FIELD)
public class EventLink implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("EVENT_LINK_ID")
  @JacksonXmlProperty(localName = "EVENT_LINK_ID")
  @XmlElement(name = "EVENT_LINK_ID")
  private Long EVENT_LINK_ID = null;

  @JsonProperty("EVENT_ID")
  @JacksonXmlProperty(localName = "EVENT_ID")
  @XmlElement(name = "EVENT_ID")
  private Long EVENT_ID = null;

  @JsonProperty("CONTACT_ID")
  @JacksonXmlProperty(localName = "CONTACT_ID")
  @XmlElement(name = "CONTACT_ID")
  private Long CONTACT_ID = null;

  @JsonProperty("ORGANISATION_ID")
  @JacksonXmlProperty(localName = "ORGANISATION_ID")
  @XmlElement(name = "ORGANISATION_ID")
  private Long ORGANISATION_ID = null;

  @JsonProperty("OPPORTUNITY_ID")
  @JacksonXmlProperty(localName = "OPPORTUNITY_ID")
  @XmlElement(name = "OPPORTUNITY_ID")
  private Long OPPORTUNITY_ID = null;

  @JsonProperty("PROJECT_ID")
  @JacksonXmlProperty(localName = "PROJECT_ID")
  @XmlElement(name = "PROJECT_ID")
  private Long PROJECT_ID = null;

  @JsonProperty("LEAD_ID")
  @JacksonXmlProperty(localName = "LEAD_ID")
  @XmlElement(name = "LEAD_ID")
  private Long LEAD_ID = null;

  public EventLink EVENT_LINK_ID(Long EVENT_LINK_ID) {
    this.EVENT_LINK_ID = EVENT_LINK_ID;
    return this;
  }

   /**
   * Get EVENT_LINK_ID
   * @return EVENT_LINK_ID
  **/
  
  public Long getEVENTLINKID() {
    return EVENT_LINK_ID;
  }

  public void setEVENTLINKID(Long EVENT_LINK_ID) {
    this.EVENT_LINK_ID = EVENT_LINK_ID;
  }

  public EventLink EVENT_ID(Long EVENT_ID) {
    this.EVENT_ID = EVENT_ID;
    return this;
  }

   /**
   * Get EVENT_ID
   * @return EVENT_ID
  **/
  
  public Long getEVENTID() {
    return EVENT_ID;
  }

  public void setEVENTID(Long EVENT_ID) {
    this.EVENT_ID = EVENT_ID;
  }

  public EventLink CONTACT_ID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
    return this;
  }

   /**
   * Get CONTACT_ID
   * @return CONTACT_ID
  **/
  
  public Long getCONTACTID() {
    return CONTACT_ID;
  }

  public void setCONTACTID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
  }

  public EventLink ORGANISATION_ID(Long ORGANISATION_ID) {
    this.ORGANISATION_ID = ORGANISATION_ID;
    return this;
  }

   /**
   * Get ORGANISATION_ID
   * @return ORGANISATION_ID
  **/
  
  public Long getORGANISATIONID() {
    return ORGANISATION_ID;
  }

  public void setORGANISATIONID(Long ORGANISATION_ID) {
    this.ORGANISATION_ID = ORGANISATION_ID;
  }

  public EventLink OPPORTUNITY_ID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
    return this;
  }

   /**
   * Get OPPORTUNITY_ID
   * @return OPPORTUNITY_ID
  **/
  
  public Long getOPPORTUNITYID() {
    return OPPORTUNITY_ID;
  }

  public void setOPPORTUNITYID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
  }

  public EventLink PROJECT_ID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
    return this;
  }

   /**
   * Get PROJECT_ID
   * @return PROJECT_ID
  **/
  
  public Long getPROJECTID() {
    return PROJECT_ID;
  }

  public void setPROJECTID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
  }

  public EventLink LEAD_ID(Long LEAD_ID) {
    this.LEAD_ID = LEAD_ID;
    return this;
  }

   /**
   * Get LEAD_ID
   * @return LEAD_ID
  **/
  
  public Long getLEADID() {
    return LEAD_ID;
  }

  public void setLEADID(Long LEAD_ID) {
    this.LEAD_ID = LEAD_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventLink eventLink = (EventLink) o;
    return Objects.equals(this.EVENT_LINK_ID, eventLink.EVENT_LINK_ID) &&
        Objects.equals(this.EVENT_ID, eventLink.EVENT_ID) &&
        Objects.equals(this.CONTACT_ID, eventLink.CONTACT_ID) &&
        Objects.equals(this.ORGANISATION_ID, eventLink.ORGANISATION_ID) &&
        Objects.equals(this.OPPORTUNITY_ID, eventLink.OPPORTUNITY_ID) &&
        Objects.equals(this.PROJECT_ID, eventLink.PROJECT_ID) &&
        Objects.equals(this.LEAD_ID, eventLink.LEAD_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(EVENT_LINK_ID, EVENT_ID, CONTACT_ID, ORGANISATION_ID, OPPORTUNITY_ID, PROJECT_ID, LEAD_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventLink {\n");
    
    sb.append("    EVENT_LINK_ID: ").append(toIndentedString(EVENT_LINK_ID)).append("\n");
    sb.append("    EVENT_ID: ").append(toIndentedString(EVENT_ID)).append("\n");
    sb.append("    CONTACT_ID: ").append(toIndentedString(CONTACT_ID)).append("\n");
    sb.append("    ORGANISATION_ID: ").append(toIndentedString(ORGANISATION_ID)).append("\n");
    sb.append("    OPPORTUNITY_ID: ").append(toIndentedString(OPPORTUNITY_ID)).append("\n");
    sb.append("    PROJECT_ID: ").append(toIndentedString(PROJECT_ID)).append("\n");
    sb.append("    LEAD_ID: ").append(toIndentedString(LEAD_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

