/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * File
 */
@JacksonXmlRootElement(localName = "File")
@XmlRootElement(name = "File")
@XmlAccessorType(XmlAccessType.FIELD)
public class File implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("FILE_NAME")
  @JacksonXmlProperty(localName = "FILE_NAME")
  @XmlElement(name = "FILE_NAME")
  private String FILE_NAME = null;

  @JsonProperty("CONTENT_TYPE")
  @JacksonXmlProperty(localName = "CONTENT_TYPE")
  @XmlElement(name = "CONTENT_TYPE")
  private String CONTENT_TYPE = null;

  @JsonProperty("FILE_CATEGORY_ID")
  @JacksonXmlProperty(localName = "FILE_CATEGORY_ID")
  @XmlElement(name = "FILE_CATEGORY_ID")
  private Long FILE_CATEGORY_ID = null;

  public File FILE_NAME(String FILE_NAME) {
    this.FILE_NAME = FILE_NAME;
    return this;
  }

   /**
   * Get FILE_NAME
   * @return FILE_NAME
  **/
  
  public String getFILENAME() {
    return FILE_NAME;
  }

  public void setFILENAME(String FILE_NAME) {
    this.FILE_NAME = FILE_NAME;
  }

  public File CONTENT_TYPE(String CONTENT_TYPE) {
    this.CONTENT_TYPE = CONTENT_TYPE;
    return this;
  }

   /**
   * Get CONTENT_TYPE
   * @return CONTENT_TYPE
  **/
  
  public String getCONTENTTYPE() {
    return CONTENT_TYPE;
  }

  public void setCONTENTTYPE(String CONTENT_TYPE) {
    this.CONTENT_TYPE = CONTENT_TYPE;
  }

  public File FILE_CATEGORY_ID(Long FILE_CATEGORY_ID) {
    this.FILE_CATEGORY_ID = FILE_CATEGORY_ID;
    return this;
  }

   /**
   * Get FILE_CATEGORY_ID
   * @return FILE_CATEGORY_ID
  **/
  
  public Long getFILECATEGORYID() {
    return FILE_CATEGORY_ID;
  }

  public void setFILECATEGORYID(Long FILE_CATEGORY_ID) {
    this.FILE_CATEGORY_ID = FILE_CATEGORY_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    File apIFile = (File) o;
    return Objects.equals(this.FILE_NAME, apIFile.FILE_NAME) &&
        Objects.equals(this.CONTENT_TYPE, apIFile.CONTENT_TYPE) &&
        Objects.equals(this.FILE_CATEGORY_ID, apIFile.FILE_CATEGORY_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(FILE_NAME, CONTENT_TYPE, FILE_CATEGORY_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class File {\n");
    
    sb.append("    FILE_NAME: ").append(toIndentedString(FILE_NAME)).append("\n");
    sb.append("    CONTENT_TYPE: ").append(toIndentedString(CONTENT_TYPE)).append("\n");
    sb.append("    FILE_CATEGORY_ID: ").append(toIndentedString(FILE_CATEGORY_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

