/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * FileAttachment
 */
@JacksonXmlRootElement(localName = "FileAttachment")
@XmlRootElement(name = "FileAttachment")
@XmlAccessorType(XmlAccessType.FIELD)
public class FileAttachment implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("FILE_ID")
  @JacksonXmlProperty(localName = "FILE_ID")
  @XmlElement(name = "FILE_ID")
  private Long FILE_ID = null;

  @JsonProperty("FILE_NAME")
  @JacksonXmlProperty(localName = "FILE_NAME")
  @XmlElement(name = "FILE_NAME")
  private String FILE_NAME = null;

  @JsonProperty("CONTENT_TYPE")
  @JacksonXmlProperty(localName = "CONTENT_TYPE")
  @XmlElement(name = "CONTENT_TYPE")
  private String CONTENT_TYPE = null;

  @JsonProperty("FILE_SIZE")
  @JacksonXmlProperty(localName = "FILE_SIZE")
  @XmlElement(name = "FILE_SIZE")
  private Long FILE_SIZE = null;

  @JsonProperty("FILE_CATEGORY_ID")
  @JacksonXmlProperty(localName = "FILE_CATEGORY_ID")
  @XmlElement(name = "FILE_CATEGORY_ID")
  private Long FILE_CATEGORY_ID = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("URL")
  @JacksonXmlProperty(localName = "URL")
  @XmlElement(name = "URL")
  private String URL = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public FileAttachment FILE_ID(Long FILE_ID) {
    this.FILE_ID = FILE_ID;
    return this;
  }

   /**
   * Get FILE_ID
   * @return FILE_ID
  **/
  
  public Long getFILEID() {
    return FILE_ID;
  }

  public void setFILEID(Long FILE_ID) {
    this.FILE_ID = FILE_ID;
  }

  public FileAttachment FILE_NAME(String FILE_NAME) {
    this.FILE_NAME = FILE_NAME;
    return this;
  }

   /**
   * Get FILE_NAME
   * @return FILE_NAME
  **/
  
  public String getFILENAME() {
    return FILE_NAME;
  }

  public void setFILENAME(String FILE_NAME) {
    this.FILE_NAME = FILE_NAME;
  }

  public FileAttachment CONTENT_TYPE(String CONTENT_TYPE) {
    this.CONTENT_TYPE = CONTENT_TYPE;
    return this;
  }

   /**
   * Get CONTENT_TYPE
   * @return CONTENT_TYPE
  **/
  
  public String getCONTENTTYPE() {
    return CONTENT_TYPE;
  }

  public void setCONTENTTYPE(String CONTENT_TYPE) {
    this.CONTENT_TYPE = CONTENT_TYPE;
  }

  public FileAttachment FILE_SIZE(Long FILE_SIZE) {
    this.FILE_SIZE = FILE_SIZE;
    return this;
  }

   /**
   * Get FILE_SIZE
   * @return FILE_SIZE
  **/
  
  public Long getFILESIZE() {
    return FILE_SIZE;
  }

  public void setFILESIZE(Long FILE_SIZE) {
    this.FILE_SIZE = FILE_SIZE;
  }

  public FileAttachment FILE_CATEGORY_ID(Long FILE_CATEGORY_ID) {
    this.FILE_CATEGORY_ID = FILE_CATEGORY_ID;
    return this;
  }

   /**
   * Get FILE_CATEGORY_ID
   * @return FILE_CATEGORY_ID
  **/
  
  public Long getFILECATEGORYID() {
    return FILE_CATEGORY_ID;
  }

  public void setFILECATEGORYID(Long FILE_CATEGORY_ID) {
    this.FILE_CATEGORY_ID = FILE_CATEGORY_ID;
  }

  public FileAttachment OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public FileAttachment DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public FileAttachment DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public FileAttachment URL(String URL) {
    this.URL = URL;
    return this;
  }

   /**
   * Get URL
   * @return URL
  **/
  
  public String getURL() {
    return URL;
  }

  public void setURL(String URL) {
    this.URL = URL;
  }

  public FileAttachment CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public FileAttachment CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileAttachment fileAttachment = (FileAttachment) o;
    return Objects.equals(this.FILE_ID, fileAttachment.FILE_ID) &&
        Objects.equals(this.FILE_NAME, fileAttachment.FILE_NAME) &&
        Objects.equals(this.CONTENT_TYPE, fileAttachment.CONTENT_TYPE) &&
        Objects.equals(this.FILE_SIZE, fileAttachment.FILE_SIZE) &&
        Objects.equals(this.FILE_CATEGORY_ID, fileAttachment.FILE_CATEGORY_ID) &&
        Objects.equals(this.OWNER_USER_ID, fileAttachment.OWNER_USER_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, fileAttachment.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, fileAttachment.DATE_UPDATED_UTC) &&
        Objects.equals(this.URL, fileAttachment.URL) &&
        Objects.equals(this.CAN_EDIT, fileAttachment.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, fileAttachment.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(FILE_ID, FILE_NAME, CONTENT_TYPE, FILE_SIZE, FILE_CATEGORY_ID, OWNER_USER_ID, DATE_CREATED_UTC, DATE_UPDATED_UTC, URL, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileAttachment {\n");
    
    sb.append("    FILE_ID: ").append(toIndentedString(FILE_ID)).append("\n");
    sb.append("    FILE_NAME: ").append(toIndentedString(FILE_NAME)).append("\n");
    sb.append("    CONTENT_TYPE: ").append(toIndentedString(CONTENT_TYPE)).append("\n");
    sb.append("    FILE_SIZE: ").append(toIndentedString(FILE_SIZE)).append("\n");
    sb.append("    FILE_CATEGORY_ID: ").append(toIndentedString(FILE_CATEGORY_ID)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    URL: ").append(toIndentedString(URL)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

