/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.io.Serializable;
import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;



/**
 * LeadStatus
 */
@JacksonXmlRootElement(localName = "LeadStatus")
@XmlRootElement(name = "LeadStatus")
@XmlAccessorType(XmlAccessType.FIELD)
public class LeadStatus implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("LEAD_STATUS_ID")
  @JacksonXmlProperty(localName = "LEAD_STATUS_ID")
  @XmlElement(name = "LEAD_STATUS_ID")
  private Long LEAD_STATUS_ID = null;

  @JsonProperty("LEAD_STATUS")
  @JacksonXmlProperty(localName = "LEAD_STATUS")
  @XmlElement(name = "LEAD_STATUS")
  private String LEAD_STATUS = null;

  @JsonProperty("DEFAULT_STATUS")
  @JacksonXmlProperty(localName = "DEFAULT_STATUS")
  @XmlElement(name = "DEFAULT_STATUS")
  private Boolean DEFAULT_STATUS = null;

  @JsonProperty("STATUS_TYPE")
  @JacksonXmlProperty(localName = "STATUS_TYPE")
  @XmlElement(name = "STATUS_TYPE")
  private Integer STATUS_TYPE = null;

  @JsonProperty("FIELD_ORDER")
  @JacksonXmlProperty(localName = "FIELD_ORDER")
  @XmlElement(name = "FIELD_ORDER")
  private Integer FIELD_ORDER = null;

  public LeadStatus LEAD_STATUS_ID(Long LEAD_STATUS_ID) {
    this.LEAD_STATUS_ID = LEAD_STATUS_ID;
    return this;
  }

   /**
   * Get LEAD_STATUS_ID
   * @return LEAD_STATUS_ID
  **/
  
  public Long getLEADSTATUSID() {
    return LEAD_STATUS_ID;
  }

  public void setLEADSTATUSID(Long LEAD_STATUS_ID) {
    this.LEAD_STATUS_ID = LEAD_STATUS_ID;
  }

  public LeadStatus LEAD_STATUS(String LEAD_STATUS) {
    this.LEAD_STATUS = LEAD_STATUS;
    return this;
  }

   /**
   * Get LEAD_STATUS
   * @return LEAD_STATUS
  **/
  
  public String getLEADSTATUS() {
    return LEAD_STATUS;
  }

  public void setLEADSTATUS(String LEAD_STATUS) {
    this.LEAD_STATUS = LEAD_STATUS;
  }

  public LeadStatus DEFAULT_STATUS(Boolean DEFAULT_STATUS) {
    this.DEFAULT_STATUS = DEFAULT_STATUS;
    return this;
  }

   /**
   * Get DEFAULT_STATUS
   * @return DEFAULT_STATUS
  **/
  
  public Boolean getDEFAULTSTATUS() {
    return DEFAULT_STATUS;
  }

  public void setDEFAULTSTATUS(Boolean DEFAULT_STATUS) {
    this.DEFAULT_STATUS = DEFAULT_STATUS;
  }

  public LeadStatus STATUS_TYPE(Integer STATUS_TYPE) {
    this.STATUS_TYPE = STATUS_TYPE;
    return this;
  }

   /**
   * Get STATUS_TYPE
   * @return STATUS_TYPE
  **/
  
  public Integer getSTATUSTYPE() {
    return STATUS_TYPE;
  }

  public void setSTATUSTYPE(Integer STATUS_TYPE) {
    this.STATUS_TYPE = STATUS_TYPE;
  }

  public LeadStatus FIELD_ORDER(Integer FIELD_ORDER) {
    this.FIELD_ORDER = FIELD_ORDER;
    return this;
  }

   /**
   * Get FIELD_ORDER
   * @return FIELD_ORDER
  **/
  
  public Integer getFIELDORDER() {
    return FIELD_ORDER;
  }

  public void setFIELDORDER(Integer FIELD_ORDER) {
    this.FIELD_ORDER = FIELD_ORDER;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeadStatus leadStatus = (LeadStatus) o;
    return Objects.equals(this.LEAD_STATUS_ID, leadStatus.LEAD_STATUS_ID) &&
        Objects.equals(this.LEAD_STATUS, leadStatus.LEAD_STATUS) &&
        Objects.equals(this.DEFAULT_STATUS, leadStatus.DEFAULT_STATUS) &&
        Objects.equals(this.STATUS_TYPE, leadStatus.STATUS_TYPE) &&
        Objects.equals(this.FIELD_ORDER, leadStatus.FIELD_ORDER);
  }

  @Override
  public int hashCode() {
    return Objects.hash(LEAD_STATUS_ID, LEAD_STATUS, DEFAULT_STATUS, STATUS_TYPE, FIELD_ORDER);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeadStatus {\n");
    
    sb.append("    LEAD_STATUS_ID: ").append(toIndentedString(LEAD_STATUS_ID)).append("\n");
    sb.append("    LEAD_STATUS: ").append(toIndentedString(LEAD_STATUS)).append("\n");
    sb.append("    DEFAULT_STATUS: ").append(toIndentedString(DEFAULT_STATUS)).append("\n");
    sb.append("    STATUS_TYPE: ").append(toIndentedString(STATUS_TYPE)).append("\n");
    sb.append("    FIELD_ORDER: ").append(toIndentedString(FIELD_ORDER)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

