/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Link
 */
@JacksonXmlRootElement(localName = "Link")
@XmlRootElement(name = "Link")
@XmlAccessorType(XmlAccessType.FIELD)
public class Link implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("LINK_ID")
  @JacksonXmlProperty(localName = "LINK_ID")
  @XmlElement(name = "LINK_ID")
  private Long LINK_ID = null;

  @JsonProperty("CONTACT_ID")
  @JacksonXmlProperty(localName = "CONTACT_ID")
  @XmlElement(name = "CONTACT_ID")
  private Long CONTACT_ID = null;

  @JsonProperty("OPPORTUNITY_ID")
  @JacksonXmlProperty(localName = "OPPORTUNITY_ID")
  @XmlElement(name = "OPPORTUNITY_ID")
  private Long OPPORTUNITY_ID = null;

  @JsonProperty("ORGANISATION_ID")
  @JacksonXmlProperty(localName = "ORGANISATION_ID")
  @XmlElement(name = "ORGANISATION_ID")
  private Long ORGANISATION_ID = null;

  @JsonProperty("PROJECT_ID")
  @JacksonXmlProperty(localName = "PROJECT_ID")
  @XmlElement(name = "PROJECT_ID")
  private Long PROJECT_ID = null;

  @JsonProperty("SECOND_PROJECT_ID")
  @JacksonXmlProperty(localName = "SECOND_PROJECT_ID")
  @XmlElement(name = "SECOND_PROJECT_ID")
  private Long SECOND_PROJECT_ID = null;

  @JsonProperty("SECOND_OPPORTUNITY_ID")
  @JacksonXmlProperty(localName = "SECOND_OPPORTUNITY_ID")
  @XmlElement(name = "SECOND_OPPORTUNITY_ID")
  private Long SECOND_OPPORTUNITY_ID = null;

  @JsonProperty("ROLE")
  @JacksonXmlProperty(localName = "ROLE")
  @XmlElement(name = "ROLE")
  private String ROLE = null;

  @JsonProperty("DETAILS")
  @JacksonXmlProperty(localName = "DETAILS")
  @XmlElement(name = "DETAILS")
  private String DETAILS = null;

  public Link LINK_ID(Long LINK_ID) {
    this.LINK_ID = LINK_ID;
    return this;
  }

   /**
   * Get LINK_ID
   * @return LINK_ID
  **/
  
  public Long getLINKID() {
    return LINK_ID;
  }

  public void setLINKID(Long LINK_ID) {
    this.LINK_ID = LINK_ID;
  }

  public Link CONTACT_ID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
    return this;
  }

   /**
   * Get CONTACT_ID
   * @return CONTACT_ID
  **/
  
  public Long getCONTACTID() {
    return CONTACT_ID;
  }

  public void setCONTACTID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
  }

  public Link OPPORTUNITY_ID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
    return this;
  }

   /**
   * Get OPPORTUNITY_ID
   * @return OPPORTUNITY_ID
  **/
  
  public Long getOPPORTUNITYID() {
    return OPPORTUNITY_ID;
  }

  public void setOPPORTUNITYID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
  }

  public Link ORGANISATION_ID(Long ORGANISATION_ID) {
    this.ORGANISATION_ID = ORGANISATION_ID;
    return this;
  }

   /**
   * Get ORGANISATION_ID
   * @return ORGANISATION_ID
  **/
  
  public Long getORGANISATIONID() {
    return ORGANISATION_ID;
  }

  public void setORGANISATIONID(Long ORGANISATION_ID) {
    this.ORGANISATION_ID = ORGANISATION_ID;
  }

  public Link PROJECT_ID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
    return this;
  }

   /**
   * Get PROJECT_ID
   * @return PROJECT_ID
  **/
  
  public Long getPROJECTID() {
    return PROJECT_ID;
  }

  public void setPROJECTID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
  }

  public Link SECOND_PROJECT_ID(Long SECOND_PROJECT_ID) {
    this.SECOND_PROJECT_ID = SECOND_PROJECT_ID;
    return this;
  }

   /**
   * Get SECOND_PROJECT_ID
   * @return SECOND_PROJECT_ID
  **/
  
  public Long getSECONDPROJECTID() {
    return SECOND_PROJECT_ID;
  }

  public void setSECONDPROJECTID(Long SECOND_PROJECT_ID) {
    this.SECOND_PROJECT_ID = SECOND_PROJECT_ID;
  }

  public Link SECOND_OPPORTUNITY_ID(Long SECOND_OPPORTUNITY_ID) {
    this.SECOND_OPPORTUNITY_ID = SECOND_OPPORTUNITY_ID;
    return this;
  }

   /**
   * Get SECOND_OPPORTUNITY_ID
   * @return SECOND_OPPORTUNITY_ID
  **/
  
  public Long getSECONDOPPORTUNITYID() {
    return SECOND_OPPORTUNITY_ID;
  }

  public void setSECONDOPPORTUNITYID(Long SECOND_OPPORTUNITY_ID) {
    this.SECOND_OPPORTUNITY_ID = SECOND_OPPORTUNITY_ID;
  }

  public Link ROLE(String ROLE) {
    this.ROLE = ROLE;
    return this;
  }

   /**
   * Get ROLE
   * @return ROLE
  **/
  
  public String getROLE() {
    return ROLE;
  }

  public void setROLE(String ROLE) {
    this.ROLE = ROLE;
  }

  public Link DETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
    return this;
  }

   /**
   * Get DETAILS
   * @return DETAILS
  **/
  
  public String getDETAILS() {
    return DETAILS;
  }

  public void setDETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Link link = (Link) o;
    return Objects.equals(this.LINK_ID, link.LINK_ID) &&
        Objects.equals(this.CONTACT_ID, link.CONTACT_ID) &&
        Objects.equals(this.OPPORTUNITY_ID, link.OPPORTUNITY_ID) &&
        Objects.equals(this.ORGANISATION_ID, link.ORGANISATION_ID) &&
        Objects.equals(this.PROJECT_ID, link.PROJECT_ID) &&
        Objects.equals(this.SECOND_PROJECT_ID, link.SECOND_PROJECT_ID) &&
        Objects.equals(this.SECOND_OPPORTUNITY_ID, link.SECOND_OPPORTUNITY_ID) &&
        Objects.equals(this.ROLE, link.ROLE) &&
        Objects.equals(this.DETAILS, link.DETAILS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(LINK_ID, CONTACT_ID, OPPORTUNITY_ID, ORGANISATION_ID, PROJECT_ID, SECOND_PROJECT_ID, SECOND_OPPORTUNITY_ID, ROLE, DETAILS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Link {\n");
    
    sb.append("    LINK_ID: ").append(toIndentedString(LINK_ID)).append("\n");
    sb.append("    CONTACT_ID: ").append(toIndentedString(CONTACT_ID)).append("\n");
    sb.append("    OPPORTUNITY_ID: ").append(toIndentedString(OPPORTUNITY_ID)).append("\n");
    sb.append("    ORGANISATION_ID: ").append(toIndentedString(ORGANISATION_ID)).append("\n");
    sb.append("    PROJECT_ID: ").append(toIndentedString(PROJECT_ID)).append("\n");
    sb.append("    SECOND_PROJECT_ID: ").append(toIndentedString(SECOND_PROJECT_ID)).append("\n");
    sb.append("    SECOND_OPPORTUNITY_ID: ").append(toIndentedString(SECOND_OPPORTUNITY_ID)).append("\n");
    sb.append("    ROLE: ").append(toIndentedString(ROLE)).append("\n");
    sb.append("    DETAILS: ").append(toIndentedString(DETAILS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

