/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Milestone
 */
@JacksonXmlRootElement(localName = "Milestone")
@XmlRootElement(name = "Milestone")
@XmlAccessorType(XmlAccessType.FIELD)
public class Milestone implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("MILESTONE_ID")
  @JacksonXmlProperty(localName = "MILESTONE_ID")
  @XmlElement(name = "MILESTONE_ID")
  private Long MILESTONE_ID = null;

  @JsonProperty("PROJECT_ID")
  @JacksonXmlProperty(localName = "PROJECT_ID")
  @XmlElement(name = "PROJECT_ID")
  private Long PROJECT_ID = null;

  @JsonProperty("TITLE")
  @JacksonXmlProperty(localName = "TITLE")
  @XmlElement(name = "TITLE")
  private String TITLE = null;

  @JsonProperty("DUE_DATE")
  @JacksonXmlProperty(localName = "DUE_DATE")
  @XmlElement(name = "DUE_DATE")
  private OffsetDateTime DUE_DATE = null;

  @JsonProperty("COMPLETED")
  @JacksonXmlProperty(localName = "COMPLETED")
  @XmlElement(name = "COMPLETED")
  private Boolean COMPLETED = null;

  @JsonProperty("COMPLETED_DATE_UTC")
  @JacksonXmlProperty(localName = "COMPLETED_DATE_UTC")
  @XmlElement(name = "COMPLETED_DATE_UTC")
  private OffsetDateTime COMPLETED_DATE_UTC = null;

  @JsonProperty("RESPONSIBLE_USER_ID")
  @JacksonXmlProperty(localName = "RESPONSIBLE_USER_ID")
  @XmlElement(name = "RESPONSIBLE_USER_ID")
  private Integer RESPONSIBLE_USER_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  public Milestone MILESTONE_ID(Long MILESTONE_ID) {
    this.MILESTONE_ID = MILESTONE_ID;
    return this;
  }

   /**
   * Get MILESTONE_ID
   * @return MILESTONE_ID
  **/
  
  public Long getMILESTONEID() {
    return MILESTONE_ID;
  }

  public void setMILESTONEID(Long MILESTONE_ID) {
    this.MILESTONE_ID = MILESTONE_ID;
  }

  public Milestone PROJECT_ID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
    return this;
  }

   /**
   * Get PROJECT_ID
   * @return PROJECT_ID
  **/
  
  public Long getPROJECTID() {
    return PROJECT_ID;
  }

  public void setPROJECTID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
  }

  public Milestone TITLE(String TITLE) {
    this.TITLE = TITLE;
    return this;
  }

   /**
   * Get TITLE
   * @return TITLE
  **/
  
  public String getTITLE() {
    return TITLE;
  }

  public void setTITLE(String TITLE) {
    this.TITLE = TITLE;
  }

  public Milestone DUE_DATE(OffsetDateTime DUE_DATE) {
    this.DUE_DATE = DUE_DATE;
    return this;
  }

   /**
   * Get DUE_DATE
   * @return DUE_DATE
  **/
  
  public OffsetDateTime getDUEDATE() {
    return DUE_DATE;
  }

  public void setDUEDATE(OffsetDateTime DUE_DATE) {
    this.DUE_DATE = DUE_DATE;
  }

  public Milestone COMPLETED(Boolean COMPLETED) {
    this.COMPLETED = COMPLETED;
    return this;
  }

   /**
   * Get COMPLETED
   * @return COMPLETED
  **/
  
  public Boolean getCOMPLETED() {
    return COMPLETED;
  }

  public void setCOMPLETED(Boolean COMPLETED) {
    this.COMPLETED = COMPLETED;
  }

  public Milestone COMPLETED_DATE_UTC(OffsetDateTime COMPLETED_DATE_UTC) {
    this.COMPLETED_DATE_UTC = COMPLETED_DATE_UTC;
    return this;
  }

   /**
   * Get COMPLETED_DATE_UTC
   * @return COMPLETED_DATE_UTC
  **/
  
  public OffsetDateTime getCOMPLETEDDATEUTC() {
    return COMPLETED_DATE_UTC;
  }

  public void setCOMPLETEDDATEUTC(OffsetDateTime COMPLETED_DATE_UTC) {
    this.COMPLETED_DATE_UTC = COMPLETED_DATE_UTC;
  }

  public Milestone RESPONSIBLE_USER_ID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
    return this;
  }

   /**
   * Get RESPONSIBLE_USER_ID
   * @return RESPONSIBLE_USER_ID
  **/
  
  public Integer getRESPONSIBLEUSERID() {
    return RESPONSIBLE_USER_ID;
  }

  public void setRESPONSIBLEUSERID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
  }

  public Milestone DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public Milestone DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Milestone milestone = (Milestone) o;
    return Objects.equals(this.MILESTONE_ID, milestone.MILESTONE_ID) &&
        Objects.equals(this.PROJECT_ID, milestone.PROJECT_ID) &&
        Objects.equals(this.TITLE, milestone.TITLE) &&
        Objects.equals(this.DUE_DATE, milestone.DUE_DATE) &&
        Objects.equals(this.COMPLETED, milestone.COMPLETED) &&
        Objects.equals(this.COMPLETED_DATE_UTC, milestone.COMPLETED_DATE_UTC) &&
        Objects.equals(this.RESPONSIBLE_USER_ID, milestone.RESPONSIBLE_USER_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, milestone.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, milestone.DATE_UPDATED_UTC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(MILESTONE_ID, PROJECT_ID, TITLE, DUE_DATE, COMPLETED, COMPLETED_DATE_UTC, RESPONSIBLE_USER_ID, DATE_CREATED_UTC, DATE_UPDATED_UTC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Milestone {\n");
    
    sb.append("    MILESTONE_ID: ").append(toIndentedString(MILESTONE_ID)).append("\n");
    sb.append("    PROJECT_ID: ").append(toIndentedString(PROJECT_ID)).append("\n");
    sb.append("    TITLE: ").append(toIndentedString(TITLE)).append("\n");
    sb.append("    DUE_DATE: ").append(toIndentedString(DUE_DATE)).append("\n");
    sb.append("    COMPLETED: ").append(toIndentedString(COMPLETED)).append("\n");
    sb.append("    COMPLETED_DATE_UTC: ").append(toIndentedString(COMPLETED_DATE_UTC)).append("\n");
    sb.append("    RESPONSIBLE_USER_ID: ").append(toIndentedString(RESPONSIBLE_USER_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

