/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * ObjectPermissions
 */
@JacksonXmlRootElement(localName = "ObjectPermissions")
@XmlRootElement(name = "ObjectPermissions")
@XmlAccessorType(XmlAccessType.FIELD)
public class ObjectPermissions implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("OBJECT_TYPE")
  @JacksonXmlProperty(localName = "OBJECT_TYPE")
  @XmlElement(name = "OBJECT_TYPE")
  private String OBJECT_TYPE = null;

  @JsonProperty("PERMISSIONS_STATE")
  @JacksonXmlProperty(localName = "PERMISSIONS_STATE")
  @XmlElement(name = "PERMISSIONS_STATE")
  private String PERMISSIONS_STATE = null;

  @JsonProperty("CAN_READ")
  @JacksonXmlProperty(localName = "CAN_READ")
  @XmlElement(name = "CAN_READ")
  private Boolean CAN_READ = null;

  @JsonProperty("CAN_CREATE")
  @JacksonXmlProperty(localName = "CAN_CREATE")
  @XmlElement(name = "CAN_CREATE")
  private Boolean CAN_CREATE = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public ObjectPermissions OBJECT_TYPE(String OBJECT_TYPE) {
    this.OBJECT_TYPE = OBJECT_TYPE;
    return this;
  }

   /**
   * Get OBJECT_TYPE
   * @return OBJECT_TYPE
  **/
  
  public String getOBJECTTYPE() {
    return OBJECT_TYPE;
  }

  public void setOBJECTTYPE(String OBJECT_TYPE) {
    this.OBJECT_TYPE = OBJECT_TYPE;
  }

  public ObjectPermissions PERMISSIONS_STATE(String PERMISSIONS_STATE) {
    this.PERMISSIONS_STATE = PERMISSIONS_STATE;
    return this;
  }

   /**
   * Get PERMISSIONS_STATE
   * @return PERMISSIONS_STATE
  **/
  
  public String getPERMISSIONSSTATE() {
    return PERMISSIONS_STATE;
  }

  public void setPERMISSIONSSTATE(String PERMISSIONS_STATE) {
    this.PERMISSIONS_STATE = PERMISSIONS_STATE;
  }

  public ObjectPermissions CAN_READ(Boolean CAN_READ) {
    this.CAN_READ = CAN_READ;
    return this;
  }

   /**
   * Get CAN_READ
   * @return CAN_READ
  **/
  
  public Boolean getCANREAD() {
    return CAN_READ;
  }

  public void setCANREAD(Boolean CAN_READ) {
    this.CAN_READ = CAN_READ;
  }

  public ObjectPermissions CAN_CREATE(Boolean CAN_CREATE) {
    this.CAN_CREATE = CAN_CREATE;
    return this;
  }

   /**
   * Get CAN_CREATE
   * @return CAN_CREATE
  **/
  
  public Boolean getCANCREATE() {
    return CAN_CREATE;
  }

  public void setCANCREATE(Boolean CAN_CREATE) {
    this.CAN_CREATE = CAN_CREATE;
  }

  public ObjectPermissions CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public ObjectPermissions CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectPermissions apIObjectPermissions = (ObjectPermissions) o;
    return Objects.equals(this.OBJECT_TYPE, apIObjectPermissions.OBJECT_TYPE) &&
        Objects.equals(this.PERMISSIONS_STATE, apIObjectPermissions.PERMISSIONS_STATE) &&
        Objects.equals(this.CAN_READ, apIObjectPermissions.CAN_READ) &&
        Objects.equals(this.CAN_CREATE, apIObjectPermissions.CAN_CREATE) &&
        Objects.equals(this.CAN_EDIT, apIObjectPermissions.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, apIObjectPermissions.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(OBJECT_TYPE, PERMISSIONS_STATE, CAN_READ, CAN_CREATE, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectPermissions {\n");
    
    sb.append("    OBJECT_TYPE: ").append(toIndentedString(OBJECT_TYPE)).append("\n");
    sb.append("    PERMISSIONS_STATE: ").append(toIndentedString(PERMISSIONS_STATE)).append("\n");
    sb.append("    CAN_READ: ").append(toIndentedString(CAN_READ)).append("\n");
    sb.append("    CAN_CREATE: ").append(toIndentedString(CAN_CREATE)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

