/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * OrganisationDate
 */
@JacksonXmlRootElement(localName = "OrganisationDate")
@XmlRootElement(name = "OrganisationDate")
@XmlAccessorType(XmlAccessType.FIELD)
public class OrganisationDate implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("DATE_ID")
  @JacksonXmlProperty(localName = "DATE_ID")
  @XmlElement(name = "DATE_ID")
  private Long DATE_ID = null;

  @JsonProperty("OCCASION_NAME")
  @JacksonXmlProperty(localName = "OCCASION_NAME")
  @XmlElement(name = "OCCASION_NAME")
  private String OCCASION_NAME = null;

  @JsonProperty("OCCASION_DATE")
  @JacksonXmlProperty(localName = "OCCASION_DATE")
  @XmlElement(name = "OCCASION_DATE")
  private OffsetDateTime OCCASION_DATE = null;

  @JsonProperty("REPEAT_YEARLY")
  @JacksonXmlProperty(localName = "REPEAT_YEARLY")
  @XmlElement(name = "REPEAT_YEARLY")
  private Boolean REPEAT_YEARLY = null;

  @JsonProperty("CREATE_TASK_YEARLY")
  @JacksonXmlProperty(localName = "CREATE_TASK_YEARLY")
  @XmlElement(name = "CREATE_TASK_YEARLY")
  private Boolean CREATE_TASK_YEARLY = null;

  public OrganisationDate DATE_ID(Long DATE_ID) {
    this.DATE_ID = DATE_ID;
    return this;
  }

   /**
   * Get DATE_ID
   * @return DATE_ID
  **/
  
  public Long getDATEID() {
    return DATE_ID;
  }

  public void setDATEID(Long DATE_ID) {
    this.DATE_ID = DATE_ID;
  }

  public OrganisationDate OCCASION_NAME(String OCCASION_NAME) {
    this.OCCASION_NAME = OCCASION_NAME;
    return this;
  }

   /**
   * Get OCCASION_NAME
   * @return OCCASION_NAME
  **/
  
  public String getOCCASIONNAME() {
    return OCCASION_NAME;
  }

  public void setOCCASIONNAME(String OCCASION_NAME) {
    this.OCCASION_NAME = OCCASION_NAME;
  }

  public OrganisationDate OCCASION_DATE(OffsetDateTime OCCASION_DATE) {
    this.OCCASION_DATE = OCCASION_DATE;
    return this;
  }

   /**
   * Get OCCASION_DATE
   * @return OCCASION_DATE
  **/
  
  public OffsetDateTime getOCCASIONDATE() {
    return OCCASION_DATE;
  }

  public void setOCCASIONDATE(OffsetDateTime OCCASION_DATE) {
    this.OCCASION_DATE = OCCASION_DATE;
  }

  public OrganisationDate REPEAT_YEARLY(Boolean REPEAT_YEARLY) {
    this.REPEAT_YEARLY = REPEAT_YEARLY;
    return this;
  }

   /**
   * Get REPEAT_YEARLY
   * @return REPEAT_YEARLY
  **/
  
  public Boolean getREPEATYEARLY() {
    return REPEAT_YEARLY;
  }

  public void setREPEATYEARLY(Boolean REPEAT_YEARLY) {
    this.REPEAT_YEARLY = REPEAT_YEARLY;
  }

  public OrganisationDate CREATE_TASK_YEARLY(Boolean CREATE_TASK_YEARLY) {
    this.CREATE_TASK_YEARLY = CREATE_TASK_YEARLY;
    return this;
  }

   /**
   * Get CREATE_TASK_YEARLY
   * @return CREATE_TASK_YEARLY
  **/
  
  public Boolean getCREATETASKYEARLY() {
    return CREATE_TASK_YEARLY;
  }

  public void setCREATETASKYEARLY(Boolean CREATE_TASK_YEARLY) {
    this.CREATE_TASK_YEARLY = CREATE_TASK_YEARLY;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationDate organisationDate = (OrganisationDate) o;
    return Objects.equals(this.DATE_ID, organisationDate.DATE_ID) &&
        Objects.equals(this.OCCASION_NAME, organisationDate.OCCASION_NAME) &&
        Objects.equals(this.OCCASION_DATE, organisationDate.OCCASION_DATE) &&
        Objects.equals(this.REPEAT_YEARLY, organisationDate.REPEAT_YEARLY) &&
        Objects.equals(this.CREATE_TASK_YEARLY, organisationDate.CREATE_TASK_YEARLY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(DATE_ID, OCCASION_NAME, OCCASION_DATE, REPEAT_YEARLY, CREATE_TASK_YEARLY);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationDate {\n");
    
    sb.append("    DATE_ID: ").append(toIndentedString(DATE_ID)).append("\n");
    sb.append("    OCCASION_NAME: ").append(toIndentedString(OCCASION_NAME)).append("\n");
    sb.append("    OCCASION_DATE: ").append(toIndentedString(OCCASION_DATE)).append("\n");
    sb.append("    REPEAT_YEARLY: ").append(toIndentedString(REPEAT_YEARLY)).append("\n");
    sb.append("    CREATE_TASK_YEARLY: ").append(toIndentedString(CREATE_TASK_YEARLY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

