/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * OrganisationLink
 */
@JacksonXmlRootElement(localName = "OrganisationLink")
@XmlRootElement(name = "OrganisationLink")
@XmlAccessorType(XmlAccessType.FIELD)
public class OrganisationLink implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("ORG_LINK_ID")
  @JacksonXmlProperty(localName = "ORG_LINK_ID")
  @XmlElement(name = "ORG_LINK_ID")
  private Long ORG_LINK_ID = null;

  @JsonProperty("FIRST_ORGANISATION_ID")
  @JacksonXmlProperty(localName = "FIRST_ORGANISATION_ID")
  @XmlElement(name = "FIRST_ORGANISATION_ID")
  private Long FIRST_ORGANISATION_ID = null;

  @JsonProperty("SECOND_ORGANISATION_ID")
  @JacksonXmlProperty(localName = "SECOND_ORGANISATION_ID")
  @XmlElement(name = "SECOND_ORGANISATION_ID")
  private Long SECOND_ORGANISATION_ID = null;

  @JsonProperty("RELATIONSHIP_ID")
  @JacksonXmlProperty(localName = "RELATIONSHIP_ID")
  @XmlElement(name = "RELATIONSHIP_ID")
  private Long RELATIONSHIP_ID = null;

  @JsonProperty("DETAILS")
  @JacksonXmlProperty(localName = "DETAILS")
  @XmlElement(name = "DETAILS")
  private String DETAILS = null;

  public OrganisationLink ORG_LINK_ID(Long ORG_LINK_ID) {
    this.ORG_LINK_ID = ORG_LINK_ID;
    return this;
  }

   /**
   * Get ORG_LINK_ID
   * @return ORG_LINK_ID
  **/
  
  public Long getORGLINKID() {
    return ORG_LINK_ID;
  }

  public void setORGLINKID(Long ORG_LINK_ID) {
    this.ORG_LINK_ID = ORG_LINK_ID;
  }

  public OrganisationLink FIRST_ORGANISATION_ID(Long FIRST_ORGANISATION_ID) {
    this.FIRST_ORGANISATION_ID = FIRST_ORGANISATION_ID;
    return this;
  }

   /**
   * Get FIRST_ORGANISATION_ID
   * @return FIRST_ORGANISATION_ID
  **/
  
  public Long getFIRSTORGANISATIONID() {
    return FIRST_ORGANISATION_ID;
  }

  public void setFIRSTORGANISATIONID(Long FIRST_ORGANISATION_ID) {
    this.FIRST_ORGANISATION_ID = FIRST_ORGANISATION_ID;
  }

  public OrganisationLink SECOND_ORGANISATION_ID(Long SECOND_ORGANISATION_ID) {
    this.SECOND_ORGANISATION_ID = SECOND_ORGANISATION_ID;
    return this;
  }

   /**
   * Get SECOND_ORGANISATION_ID
   * @return SECOND_ORGANISATION_ID
  **/
  
  public Long getSECONDORGANISATIONID() {
    return SECOND_ORGANISATION_ID;
  }

  public void setSECONDORGANISATIONID(Long SECOND_ORGANISATION_ID) {
    this.SECOND_ORGANISATION_ID = SECOND_ORGANISATION_ID;
  }

  public OrganisationLink RELATIONSHIP_ID(Long RELATIONSHIP_ID) {
    this.RELATIONSHIP_ID = RELATIONSHIP_ID;
    return this;
  }

   /**
   * Get RELATIONSHIP_ID
   * @return RELATIONSHIP_ID
  **/
  
  public Long getRELATIONSHIPID() {
    return RELATIONSHIP_ID;
  }

  public void setRELATIONSHIPID(Long RELATIONSHIP_ID) {
    this.RELATIONSHIP_ID = RELATIONSHIP_ID;
  }

  public OrganisationLink DETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
    return this;
  }

   /**
   * Get DETAILS
   * @return DETAILS
  **/
  
  public String getDETAILS() {
    return DETAILS;
  }

  public void setDETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationLink organisationLink = (OrganisationLink) o;
    return Objects.equals(this.ORG_LINK_ID, organisationLink.ORG_LINK_ID) &&
        Objects.equals(this.FIRST_ORGANISATION_ID, organisationLink.FIRST_ORGANISATION_ID) &&
        Objects.equals(this.SECOND_ORGANISATION_ID, organisationLink.SECOND_ORGANISATION_ID) &&
        Objects.equals(this.RELATIONSHIP_ID, organisationLink.RELATIONSHIP_ID) &&
        Objects.equals(this.DETAILS, organisationLink.DETAILS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ORG_LINK_ID, FIRST_ORGANISATION_ID, SECOND_ORGANISATION_ID, RELATIONSHIP_ID, DETAILS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationLink {\n");
    
    sb.append("    ORG_LINK_ID: ").append(toIndentedString(ORG_LINK_ID)).append("\n");
    sb.append("    FIRST_ORGANISATION_ID: ").append(toIndentedString(FIRST_ORGANISATION_ID)).append("\n");
    sb.append("    SECOND_ORGANISATION_ID: ").append(toIndentedString(SECOND_ORGANISATION_ID)).append("\n");
    sb.append("    RELATIONSHIP_ID: ").append(toIndentedString(RELATIONSHIP_ID)).append("\n");
    sb.append("    DETAILS: ").append(toIndentedString(DETAILS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

