/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Pipeline
 */
@JacksonXmlRootElement(localName = "Pipeline")
@XmlRootElement(name = "Pipeline")
@XmlAccessorType(XmlAccessType.FIELD)
public class Pipeline implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("PIPELINE_ID")
  @JacksonXmlProperty(localName = "PIPELINE_ID")
  @XmlElement(name = "PIPELINE_ID")
  private Long PIPELINE_ID = null;

  @JsonProperty("PIPELINE_NAME")
  @JacksonXmlProperty(localName = "PIPELINE_NAME")
  @XmlElement(name = "PIPELINE_NAME")
  private String PIPELINE_NAME = null;

  @JsonProperty("FOR_OPPORTUNITIES")
  @JacksonXmlProperty(localName = "FOR_OPPORTUNITIES")
  @XmlElement(name = "FOR_OPPORTUNITIES")
  private Boolean FOR_OPPORTUNITIES = null;

  @JsonProperty("FOR_PROJECTS")
  @JacksonXmlProperty(localName = "FOR_PROJECTS")
  @XmlElement(name = "FOR_PROJECTS")
  private Boolean FOR_PROJECTS = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  public Pipeline PIPELINE_ID(Long PIPELINE_ID) {
    this.PIPELINE_ID = PIPELINE_ID;
    return this;
  }

   /**
   * Get PIPELINE_ID
   * @return PIPELINE_ID
  **/
  
  public Long getPIPELINEID() {
    return PIPELINE_ID;
  }

  public void setPIPELINEID(Long PIPELINE_ID) {
    this.PIPELINE_ID = PIPELINE_ID;
  }

  public Pipeline PIPELINE_NAME(String PIPELINE_NAME) {
    this.PIPELINE_NAME = PIPELINE_NAME;
    return this;
  }

   /**
   * Get PIPELINE_NAME
   * @return PIPELINE_NAME
  **/
  
  public String getPIPELINENAME() {
    return PIPELINE_NAME;
  }

  public void setPIPELINENAME(String PIPELINE_NAME) {
    this.PIPELINE_NAME = PIPELINE_NAME;
  }

  public Pipeline FOR_OPPORTUNITIES(Boolean FOR_OPPORTUNITIES) {
    this.FOR_OPPORTUNITIES = FOR_OPPORTUNITIES;
    return this;
  }

   /**
   * Get FOR_OPPORTUNITIES
   * @return FOR_OPPORTUNITIES
  **/
  
  public Boolean getFOROPPORTUNITIES() {
    return FOR_OPPORTUNITIES;
  }

  public void setFOROPPORTUNITIES(Boolean FOR_OPPORTUNITIES) {
    this.FOR_OPPORTUNITIES = FOR_OPPORTUNITIES;
  }

  public Pipeline FOR_PROJECTS(Boolean FOR_PROJECTS) {
    this.FOR_PROJECTS = FOR_PROJECTS;
    return this;
  }

   /**
   * Get FOR_PROJECTS
   * @return FOR_PROJECTS
  **/
  
  public Boolean getFORPROJECTS() {
    return FOR_PROJECTS;
  }

  public void setFORPROJECTS(Boolean FOR_PROJECTS) {
    this.FOR_PROJECTS = FOR_PROJECTS;
  }

  public Pipeline OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pipeline pipeline = (Pipeline) o;
    return Objects.equals(this.PIPELINE_ID, pipeline.PIPELINE_ID) &&
        Objects.equals(this.PIPELINE_NAME, pipeline.PIPELINE_NAME) &&
        Objects.equals(this.FOR_OPPORTUNITIES, pipeline.FOR_OPPORTUNITIES) &&
        Objects.equals(this.FOR_PROJECTS, pipeline.FOR_PROJECTS) &&
        Objects.equals(this.OWNER_USER_ID, pipeline.OWNER_USER_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PIPELINE_ID, PIPELINE_NAME, FOR_OPPORTUNITIES, FOR_PROJECTS, OWNER_USER_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pipeline {\n");
    
    sb.append("    PIPELINE_ID: ").append(toIndentedString(PIPELINE_ID)).append("\n");
    sb.append("    PIPELINE_NAME: ").append(toIndentedString(PIPELINE_NAME)).append("\n");
    sb.append("    FOR_OPPORTUNITIES: ").append(toIndentedString(FOR_OPPORTUNITIES)).append("\n");
    sb.append("    FOR_PROJECTS: ").append(toIndentedString(FOR_PROJECTS)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

