/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.insightly.model.CustomField;
import com.insightly.model.Link;
import com.insightly.model.Tag;


import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Project
 */
@JacksonXmlRootElement(localName = "Project")
@XmlRootElement(name = "Project")
@XmlAccessorType(XmlAccessType.FIELD)
public class Project implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("PROJECT_ID")
  @JacksonXmlProperty(localName = "PROJECT_ID")
  @XmlElement(name = "PROJECT_ID")
  private Long PROJECT_ID = null;

  @JsonProperty("PROJECT_NAME")
  @JacksonXmlProperty(localName = "PROJECT_NAME")
  @XmlElement(name = "PROJECT_NAME")
  private String PROJECT_NAME = null;

  @JsonProperty("STATUS")
  @JacksonXmlProperty(localName = "STATUS")
  @XmlElement(name = "STATUS")
  private String STATUS = null;

  @JsonProperty("PROJECT_DETAILS")
  @JacksonXmlProperty(localName = "PROJECT_DETAILS")
  @XmlElement(name = "PROJECT_DETAILS")
  private String PROJECT_DETAILS = null;

  @JsonProperty("OPPORTUNITY_ID")
  @JacksonXmlProperty(localName = "OPPORTUNITY_ID")
  @XmlElement(name = "OPPORTUNITY_ID")
  private Long OPPORTUNITY_ID = null;

  @JsonProperty("STARTED_DATE")
  @JacksonXmlProperty(localName = "STARTED_DATE")
  @XmlElement(name = "STARTED_DATE")
  private OffsetDateTime STARTED_DATE = null;

  @JsonProperty("COMPLETED_DATE")
  @JacksonXmlProperty(localName = "COMPLETED_DATE")
  @XmlElement(name = "COMPLETED_DATE")
  private OffsetDateTime COMPLETED_DATE = null;

  @JsonProperty("IMAGE_URL")
  @JacksonXmlProperty(localName = "IMAGE_URL")
  @XmlElement(name = "IMAGE_URL")
  private String IMAGE_URL = null;

  @JsonProperty("RESPONSIBLE_USER_ID")
  @JacksonXmlProperty(localName = "RESPONSIBLE_USER_ID")
  @XmlElement(name = "RESPONSIBLE_USER_ID")
  private Integer RESPONSIBLE_USER_ID = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("CATEGORY_ID")
  @JacksonXmlProperty(localName = "CATEGORY_ID")
  @XmlElement(name = "CATEGORY_ID")
  private Long CATEGORY_ID = null;

  @JsonProperty("PIPELINE_ID")
  @JacksonXmlProperty(localName = "PIPELINE_ID")
  @XmlElement(name = "PIPELINE_ID")
  private Long PIPELINE_ID = null;

  @JsonProperty("STAGE_ID")
  @JacksonXmlProperty(localName = "STAGE_ID")
  @XmlElement(name = "STAGE_ID")
  private Long STAGE_ID = null;

  @JsonProperty("VISIBLE_TO")
  @JacksonXmlProperty(localName = "VISIBLE_TO")
  @XmlElement(name = "VISIBLE_TO")
  private String VISIBLE_TO = null;

  @JsonProperty("VISIBLE_TEAM_ID")
  @JacksonXmlProperty(localName = "VISIBLE_TEAM_ID")
  @XmlElement(name = "VISIBLE_TEAM_ID")
  private Long VISIBLE_TEAM_ID = null;

  @JsonProperty("VISIBLE_USER_IDS")
  @JacksonXmlProperty(localName = "VISIBLE_USER_IDS")
  @XmlElement(name = "VISIBLE_USER_IDS")
  private String VISIBLE_USER_IDS = null;

  @JsonProperty("CUSTOMFIELDS")
  @JacksonXmlProperty(localName = "CUSTOMFIELDS")
  @XmlElement(name = "CUSTOMFIELDS")
  private List<CustomField> CUSTOMFIELDS = null;

  @JsonProperty("TAGS")
  @JacksonXmlProperty(localName = "TAGS")
  @XmlElement(name = "TAGS")
  private List<Tag> TAGS = null;

  @JsonProperty("LINKS")
  @JacksonXmlProperty(localName = "LINKS")
  @XmlElement(name = "LINKS")
  private List<Link> LINKS = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public Project PROJECT_ID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
    return this;
  }

   /**
   * Get PROJECT_ID
   * @return PROJECT_ID
  **/
  
  public Long getPROJECTID() {
    return PROJECT_ID;
  }

  public void setPROJECTID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
  }

  public Project PROJECT_NAME(String PROJECT_NAME) {
    this.PROJECT_NAME = PROJECT_NAME;
    return this;
  }

   /**
   * Get PROJECT_NAME
   * @return PROJECT_NAME
  **/
  
  public String getPROJECTNAME() {
    return PROJECT_NAME;
  }

  public void setPROJECTNAME(String PROJECT_NAME) {
    this.PROJECT_NAME = PROJECT_NAME;
  }

  public Project STATUS(String STATUS) {
    this.STATUS = STATUS;
    return this;
  }

   /**
   * Get STATUS
   * @return STATUS
  **/
  
  public String getSTATUS() {
    return STATUS;
  }

  public void setSTATUS(String STATUS) {
    this.STATUS = STATUS;
  }

  public Project PROJECT_DETAILS(String PROJECT_DETAILS) {
    this.PROJECT_DETAILS = PROJECT_DETAILS;
    return this;
  }

   /**
   * Get PROJECT_DETAILS
   * @return PROJECT_DETAILS
  **/
  
  public String getPROJECTDETAILS() {
    return PROJECT_DETAILS;
  }

  public void setPROJECTDETAILS(String PROJECT_DETAILS) {
    this.PROJECT_DETAILS = PROJECT_DETAILS;
  }

  public Project OPPORTUNITY_ID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
    return this;
  }

   /**
   * Get OPPORTUNITY_ID
   * @return OPPORTUNITY_ID
  **/
  
  public Long getOPPORTUNITYID() {
    return OPPORTUNITY_ID;
  }

  public void setOPPORTUNITYID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
  }

  public Project STARTED_DATE(OffsetDateTime STARTED_DATE) {
    this.STARTED_DATE = STARTED_DATE;
    return this;
  }

   /**
   * Get STARTED_DATE
   * @return STARTED_DATE
  **/
  
  public OffsetDateTime getSTARTEDDATE() {
    return STARTED_DATE;
  }

  public void setSTARTEDDATE(OffsetDateTime STARTED_DATE) {
    this.STARTED_DATE = STARTED_DATE;
  }

  public Project COMPLETED_DATE(OffsetDateTime COMPLETED_DATE) {
    this.COMPLETED_DATE = COMPLETED_DATE;
    return this;
  }

   /**
   * Get COMPLETED_DATE
   * @return COMPLETED_DATE
  **/
  
  public OffsetDateTime getCOMPLETEDDATE() {
    return COMPLETED_DATE;
  }

  public void setCOMPLETEDDATE(OffsetDateTime COMPLETED_DATE) {
    this.COMPLETED_DATE = COMPLETED_DATE;
  }

  public Project IMAGE_URL(String IMAGE_URL) {
    this.IMAGE_URL = IMAGE_URL;
    return this;
  }

   /**
   * Get IMAGE_URL
   * @return IMAGE_URL
  **/
  
  public String getIMAGEURL() {
    return IMAGE_URL;
  }

  public void setIMAGEURL(String IMAGE_URL) {
    this.IMAGE_URL = IMAGE_URL;
  }

  public Project RESPONSIBLE_USER_ID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
    return this;
  }

   /**
   * Get RESPONSIBLE_USER_ID
   * @return RESPONSIBLE_USER_ID
  **/
  
  public Integer getRESPONSIBLEUSERID() {
    return RESPONSIBLE_USER_ID;
  }

  public void setRESPONSIBLEUSERID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
  }

  public Project OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public Project DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public Project DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public Project CATEGORY_ID(Long CATEGORY_ID) {
    this.CATEGORY_ID = CATEGORY_ID;
    return this;
  }

   /**
   * Get CATEGORY_ID
   * @return CATEGORY_ID
  **/
  
  public Long getCATEGORYID() {
    return CATEGORY_ID;
  }

  public void setCATEGORYID(Long CATEGORY_ID) {
    this.CATEGORY_ID = CATEGORY_ID;
  }

  public Project PIPELINE_ID(Long PIPELINE_ID) {
    this.PIPELINE_ID = PIPELINE_ID;
    return this;
  }

   /**
   * Get PIPELINE_ID
   * @return PIPELINE_ID
  **/
  
  public Long getPIPELINEID() {
    return PIPELINE_ID;
  }

  public void setPIPELINEID(Long PIPELINE_ID) {
    this.PIPELINE_ID = PIPELINE_ID;
  }

  public Project STAGE_ID(Long STAGE_ID) {
    this.STAGE_ID = STAGE_ID;
    return this;
  }

   /**
   * Get STAGE_ID
   * @return STAGE_ID
  **/
  
  public Long getSTAGEID() {
    return STAGE_ID;
  }

  public void setSTAGEID(Long STAGE_ID) {
    this.STAGE_ID = STAGE_ID;
  }

  public Project VISIBLE_TO(String VISIBLE_TO) {
    this.VISIBLE_TO = VISIBLE_TO;
    return this;
  }

   /**
   * Get VISIBLE_TO
   * @return VISIBLE_TO
  **/
  
  public String getVISIBLETO() {
    return VISIBLE_TO;
  }

  public void setVISIBLETO(String VISIBLE_TO) {
    this.VISIBLE_TO = VISIBLE_TO;
  }

  public Project VISIBLE_TEAM_ID(Long VISIBLE_TEAM_ID) {
    this.VISIBLE_TEAM_ID = VISIBLE_TEAM_ID;
    return this;
  }

   /**
   * Get VISIBLE_TEAM_ID
   * @return VISIBLE_TEAM_ID
  **/
  
  public Long getVISIBLETEAMID() {
    return VISIBLE_TEAM_ID;
  }

  public void setVISIBLETEAMID(Long VISIBLE_TEAM_ID) {
    this.VISIBLE_TEAM_ID = VISIBLE_TEAM_ID;
  }

  public Project VISIBLE_USER_IDS(String VISIBLE_USER_IDS) {
    this.VISIBLE_USER_IDS = VISIBLE_USER_IDS;
    return this;
  }

   /**
   * Get VISIBLE_USER_IDS
   * @return VISIBLE_USER_IDS
  **/
  
  public String getVISIBLEUSERIDS() {
    return VISIBLE_USER_IDS;
  }

  public void setVISIBLEUSERIDS(String VISIBLE_USER_IDS) {
    this.VISIBLE_USER_IDS = VISIBLE_USER_IDS;
  }

  public Project CUSTOMFIELDS(List<CustomField> CUSTOMFIELDS) {
    this.CUSTOMFIELDS = CUSTOMFIELDS;
    return this;
  }

  public Project addCUSTOMFIELDSItem(CustomField CUSTOMFIELDSItem) {
    if (this.CUSTOMFIELDS == null) {
      this.CUSTOMFIELDS = new ArrayList<CustomField>();
    }
    this.CUSTOMFIELDS.add(CUSTOMFIELDSItem);
    return this;
  }

   /**
   * Get CUSTOMFIELDS
   * @return CUSTOMFIELDS
  **/
  
  public List<CustomField> getCUSTOMFIELDS() {
    return CUSTOMFIELDS;
  }

  public void setCUSTOMFIELDS(List<CustomField> CUSTOMFIELDS) {
    this.CUSTOMFIELDS = CUSTOMFIELDS;
  }

  public Project TAGS(List<Tag> TAGS) {
    this.TAGS = TAGS;
    return this;
  }

  public Project addTAGSItem(Tag TAGSItem) {
    if (this.TAGS == null) {
      this.TAGS = new ArrayList<Tag>();
    }
    this.TAGS.add(TAGSItem);
    return this;
  }

   /**
   * Get TAGS
   * @return TAGS
  **/
  
  public List<Tag> getTAGS() {
    return TAGS;
  }

  public void setTAGS(List<Tag> TAGS) {
    this.TAGS = TAGS;
  }

  public Project LINKS(List<Link> LINKS) {
    this.LINKS = LINKS;
    return this;
  }

  public Project addLINKSItem(Link LINKSItem) {
    if (this.LINKS == null) {
      this.LINKS = new ArrayList<Link>();
    }
    this.LINKS.add(LINKSItem);
    return this;
  }

   /**
   * Get LINKS
   * @return LINKS
  **/
  
  public List<Link> getLINKS() {
    return LINKS;
  }

  public void setLINKS(List<Link> LINKS) {
    this.LINKS = LINKS;
  }

  public Project CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public Project CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Project project = (Project) o;
    return Objects.equals(this.PROJECT_ID, project.PROJECT_ID) &&
        Objects.equals(this.PROJECT_NAME, project.PROJECT_NAME) &&
        Objects.equals(this.STATUS, project.STATUS) &&
        Objects.equals(this.PROJECT_DETAILS, project.PROJECT_DETAILS) &&
        Objects.equals(this.OPPORTUNITY_ID, project.OPPORTUNITY_ID) &&
        Objects.equals(this.STARTED_DATE, project.STARTED_DATE) &&
        Objects.equals(this.COMPLETED_DATE, project.COMPLETED_DATE) &&
        Objects.equals(this.IMAGE_URL, project.IMAGE_URL) &&
        Objects.equals(this.RESPONSIBLE_USER_ID, project.RESPONSIBLE_USER_ID) &&
        Objects.equals(this.OWNER_USER_ID, project.OWNER_USER_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, project.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, project.DATE_UPDATED_UTC) &&
        Objects.equals(this.CATEGORY_ID, project.CATEGORY_ID) &&
        Objects.equals(this.PIPELINE_ID, project.PIPELINE_ID) &&
        Objects.equals(this.STAGE_ID, project.STAGE_ID) &&
        Objects.equals(this.VISIBLE_TO, project.VISIBLE_TO) &&
        Objects.equals(this.VISIBLE_TEAM_ID, project.VISIBLE_TEAM_ID) &&
        Objects.equals(this.VISIBLE_USER_IDS, project.VISIBLE_USER_IDS) &&
        Objects.equals(this.CUSTOMFIELDS, project.CUSTOMFIELDS) &&
        Objects.equals(this.TAGS, project.TAGS) &&
        Objects.equals(this.LINKS, project.LINKS) &&
        Objects.equals(this.CAN_EDIT, project.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, project.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PROJECT_ID, PROJECT_NAME, STATUS, PROJECT_DETAILS, OPPORTUNITY_ID, STARTED_DATE, COMPLETED_DATE, IMAGE_URL, RESPONSIBLE_USER_ID, OWNER_USER_ID, DATE_CREATED_UTC, DATE_UPDATED_UTC, CATEGORY_ID, PIPELINE_ID, STAGE_ID, VISIBLE_TO, VISIBLE_TEAM_ID, VISIBLE_USER_IDS, CUSTOMFIELDS, TAGS, LINKS, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Project {\n");
    
    sb.append("    PROJECT_ID: ").append(toIndentedString(PROJECT_ID)).append("\n");
    sb.append("    PROJECT_NAME: ").append(toIndentedString(PROJECT_NAME)).append("\n");
    sb.append("    STATUS: ").append(toIndentedString(STATUS)).append("\n");
    sb.append("    PROJECT_DETAILS: ").append(toIndentedString(PROJECT_DETAILS)).append("\n");
    sb.append("    OPPORTUNITY_ID: ").append(toIndentedString(OPPORTUNITY_ID)).append("\n");
    sb.append("    STARTED_DATE: ").append(toIndentedString(STARTED_DATE)).append("\n");
    sb.append("    COMPLETED_DATE: ").append(toIndentedString(COMPLETED_DATE)).append("\n");
    sb.append("    IMAGE_URL: ").append(toIndentedString(IMAGE_URL)).append("\n");
    sb.append("    RESPONSIBLE_USER_ID: ").append(toIndentedString(RESPONSIBLE_USER_ID)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    CATEGORY_ID: ").append(toIndentedString(CATEGORY_ID)).append("\n");
    sb.append("    PIPELINE_ID: ").append(toIndentedString(PIPELINE_ID)).append("\n");
    sb.append("    STAGE_ID: ").append(toIndentedString(STAGE_ID)).append("\n");
    sb.append("    VISIBLE_TO: ").append(toIndentedString(VISIBLE_TO)).append("\n");
    sb.append("    VISIBLE_TEAM_ID: ").append(toIndentedString(VISIBLE_TEAM_ID)).append("\n");
    sb.append("    VISIBLE_USER_IDS: ").append(toIndentedString(VISIBLE_USER_IDS)).append("\n");
    sb.append("    CUSTOMFIELDS: ").append(toIndentedString(CUSTOMFIELDS)).append("\n");
    sb.append("    TAGS: ").append(toIndentedString(TAGS)).append("\n");
    sb.append("    LINKS: ").append(toIndentedString(LINKS)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

