/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Relationship
 */
@JacksonXmlRootElement(localName = "Relationship")
@XmlRootElement(name = "Relationship")
@XmlAccessorType(XmlAccessType.FIELD)
public class Relationship implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("RELATIONSHIP_ID")
  @JacksonXmlProperty(localName = "RELATIONSHIP_ID")
  @XmlElement(name = "RELATIONSHIP_ID")
  private Long RELATIONSHIP_ID = null;

  @JsonProperty("FORWARD_TITLE")
  @JacksonXmlProperty(localName = "FORWARD_TITLE")
  @XmlElement(name = "FORWARD_TITLE")
  private String FORWARD_TITLE = null;

  @JsonProperty("FORWARD")
  @JacksonXmlProperty(localName = "FORWARD")
  @XmlElement(name = "FORWARD")
  private String FORWARD = null;

  @JsonProperty("REVERSE_TITLE")
  @JacksonXmlProperty(localName = "REVERSE_TITLE")
  @XmlElement(name = "REVERSE_TITLE")
  private String REVERSE_TITLE = null;

  @JsonProperty("REVERSE")
  @JacksonXmlProperty(localName = "REVERSE")
  @XmlElement(name = "REVERSE")
  private String REVERSE = null;

  @JsonProperty("FOR_CONTACTS")
  @JacksonXmlProperty(localName = "FOR_CONTACTS")
  @XmlElement(name = "FOR_CONTACTS")
  private Boolean FOR_CONTACTS = null;

  @JsonProperty("FOR_ORGANISATIONS")
  @JacksonXmlProperty(localName = "FOR_ORGANISATIONS")
  @XmlElement(name = "FOR_ORGANISATIONS")
  private Boolean FOR_ORGANISATIONS = null;

  public Relationship RELATIONSHIP_ID(Long RELATIONSHIP_ID) {
    this.RELATIONSHIP_ID = RELATIONSHIP_ID;
    return this;
  }

   /**
   * Get RELATIONSHIP_ID
   * @return RELATIONSHIP_ID
  **/
  
  public Long getRELATIONSHIPID() {
    return RELATIONSHIP_ID;
  }

  public void setRELATIONSHIPID(Long RELATIONSHIP_ID) {
    this.RELATIONSHIP_ID = RELATIONSHIP_ID;
  }

  public Relationship FORWARD_TITLE(String FORWARD_TITLE) {
    this.FORWARD_TITLE = FORWARD_TITLE;
    return this;
  }

   /**
   * Get FORWARD_TITLE
   * @return FORWARD_TITLE
  **/
  
  public String getFORWARDTITLE() {
    return FORWARD_TITLE;
  }

  public void setFORWARDTITLE(String FORWARD_TITLE) {
    this.FORWARD_TITLE = FORWARD_TITLE;
  }

  public Relationship FORWARD(String FORWARD) {
    this.FORWARD = FORWARD;
    return this;
  }

   /**
   * Get FORWARD
   * @return FORWARD
  **/
  
  public String getFORWARD() {
    return FORWARD;
  }

  public void setFORWARD(String FORWARD) {
    this.FORWARD = FORWARD;
  }

  public Relationship REVERSE_TITLE(String REVERSE_TITLE) {
    this.REVERSE_TITLE = REVERSE_TITLE;
    return this;
  }

   /**
   * Get REVERSE_TITLE
   * @return REVERSE_TITLE
  **/
  
  public String getREVERSETITLE() {
    return REVERSE_TITLE;
  }

  public void setREVERSETITLE(String REVERSE_TITLE) {
    this.REVERSE_TITLE = REVERSE_TITLE;
  }

  public Relationship REVERSE(String REVERSE) {
    this.REVERSE = REVERSE;
    return this;
  }

   /**
   * Get REVERSE
   * @return REVERSE
  **/
  
  public String getREVERSE() {
    return REVERSE;
  }

  public void setREVERSE(String REVERSE) {
    this.REVERSE = REVERSE;
  }

  public Relationship FOR_CONTACTS(Boolean FOR_CONTACTS) {
    this.FOR_CONTACTS = FOR_CONTACTS;
    return this;
  }

   /**
   * Get FOR_CONTACTS
   * @return FOR_CONTACTS
  **/
  
  public Boolean getFORCONTACTS() {
    return FOR_CONTACTS;
  }

  public void setFORCONTACTS(Boolean FOR_CONTACTS) {
    this.FOR_CONTACTS = FOR_CONTACTS;
  }

  public Relationship FOR_ORGANISATIONS(Boolean FOR_ORGANISATIONS) {
    this.FOR_ORGANISATIONS = FOR_ORGANISATIONS;
    return this;
  }

   /**
   * Get FOR_ORGANISATIONS
   * @return FOR_ORGANISATIONS
  **/
  
  public Boolean getFORORGANISATIONS() {
    return FOR_ORGANISATIONS;
  }

  public void setFORORGANISATIONS(Boolean FOR_ORGANISATIONS) {
    this.FOR_ORGANISATIONS = FOR_ORGANISATIONS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relationship relationship = (Relationship) o;
    return Objects.equals(this.RELATIONSHIP_ID, relationship.RELATIONSHIP_ID) &&
        Objects.equals(this.FORWARD_TITLE, relationship.FORWARD_TITLE) &&
        Objects.equals(this.FORWARD, relationship.FORWARD) &&
        Objects.equals(this.REVERSE_TITLE, relationship.REVERSE_TITLE) &&
        Objects.equals(this.REVERSE, relationship.REVERSE) &&
        Objects.equals(this.FOR_CONTACTS, relationship.FOR_CONTACTS) &&
        Objects.equals(this.FOR_ORGANISATIONS, relationship.FOR_ORGANISATIONS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RELATIONSHIP_ID, FORWARD_TITLE, FORWARD, REVERSE_TITLE, REVERSE, FOR_CONTACTS, FOR_ORGANISATIONS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relationship {\n");
    
    sb.append("    RELATIONSHIP_ID: ").append(toIndentedString(RELATIONSHIP_ID)).append("\n");
    sb.append("    FORWARD_TITLE: ").append(toIndentedString(FORWARD_TITLE)).append("\n");
    sb.append("    FORWARD: ").append(toIndentedString(FORWARD)).append("\n");
    sb.append("    REVERSE_TITLE: ").append(toIndentedString(REVERSE_TITLE)).append("\n");
    sb.append("    REVERSE: ").append(toIndentedString(REVERSE)).append("\n");
    sb.append("    FOR_CONTACTS: ").append(toIndentedString(FOR_CONTACTS)).append("\n");
    sb.append("    FOR_ORGANISATIONS: ").append(toIndentedString(FOR_ORGANISATIONS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

