/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Tag
 */
@JacksonXmlRootElement(localName = "Tag")
@XmlRootElement(name = "Tag")
@XmlAccessorType(XmlAccessType.FIELD)
public class Tag implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("TAG_NAME")
  @JacksonXmlProperty(localName = "TAG_NAME")
  @XmlElement(name = "TAG_NAME")
  private String TAG_NAME = null;

  public Tag TAG_NAME(String TAG_NAME) {
    this.TAG_NAME = TAG_NAME;
    return this;
  }

   /**
   * Get TAG_NAME
   * @return TAG_NAME
  **/
  
  public String getTAGNAME() {
    return TAG_NAME;
  }

  public void setTAGNAME(String TAG_NAME) {
    this.TAG_NAME = TAG_NAME;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tag tag = (Tag) o;
    return Objects.equals(this.TAG_NAME, tag.TAG_NAME);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TAG_NAME);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tag {\n");
    
    sb.append("    TAG_NAME: ").append(toIndentedString(TAG_NAME)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

