/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.insightly.model.TaskLink;


import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Task
 */
@JacksonXmlRootElement(localName = "Task")
@XmlRootElement(name = "Task")
@XmlAccessorType(XmlAccessType.FIELD)
public class Task implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("TASK_ID")
  @JacksonXmlProperty(localName = "TASK_ID")
  @XmlElement(name = "TASK_ID")
  private Long TASK_ID = null;

  @JsonProperty("TITLE")
  @JacksonXmlProperty(localName = "TITLE")
  @XmlElement(name = "TITLE")
  private String TITLE = null;

  @JsonProperty("CATEGORY_ID")
  @JacksonXmlProperty(localName = "CATEGORY_ID")
  @XmlElement(name = "CATEGORY_ID")
  private Long CATEGORY_ID = null;

  @JsonProperty("DUE_DATE")
  @JacksonXmlProperty(localName = "DUE_DATE")
  @XmlElement(name = "DUE_DATE")
  private OffsetDateTime DUE_DATE = null;

  @JsonProperty("COMPLETED_DATE_UTC")
  @JacksonXmlProperty(localName = "COMPLETED_DATE_UTC")
  @XmlElement(name = "COMPLETED_DATE_UTC")
  private OffsetDateTime COMPLETED_DATE_UTC = null;

  @JsonProperty("PUBLICLY_VISIBLE")
  @JacksonXmlProperty(localName = "PUBLICLY_VISIBLE")
  @XmlElement(name = "PUBLICLY_VISIBLE")
  private Boolean PUBLICLY_VISIBLE = null;

  @JsonProperty("COMPLETED")
  @JacksonXmlProperty(localName = "COMPLETED")
  @XmlElement(name = "COMPLETED")
  private Boolean COMPLETED = null;

  @JsonProperty("PROJECT_ID")
  @JacksonXmlProperty(localName = "PROJECT_ID")
  @XmlElement(name = "PROJECT_ID")
  private Long PROJECT_ID = null;

  @JsonProperty("OPPORTUNITY_ID")
  @JacksonXmlProperty(localName = "OPPORTUNITY_ID")
  @XmlElement(name = "OPPORTUNITY_ID")
  private Long OPPORTUNITY_ID = null;

  @JsonProperty("MILESTONE_ID")
  @JacksonXmlProperty(localName = "MILESTONE_ID")
  @XmlElement(name = "MILESTONE_ID")
  private Long MILESTONE_ID = null;

  @JsonProperty("PIPELINE_ID")
  @JacksonXmlProperty(localName = "PIPELINE_ID")
  @XmlElement(name = "PIPELINE_ID")
  private Long PIPELINE_ID = null;

  @JsonProperty("STAGE_ID")
  @JacksonXmlProperty(localName = "STAGE_ID")
  @XmlElement(name = "STAGE_ID")
  private Long STAGE_ID = null;

  @JsonProperty("DETAILS")
  @JacksonXmlProperty(localName = "DETAILS")
  @XmlElement(name = "DETAILS")
  private String DETAILS = null;

  @JsonProperty("STATUS")
  @JacksonXmlProperty(localName = "STATUS")
  @XmlElement(name = "STATUS")
  private String STATUS = null;

  @JsonProperty("PRIORITY")
  @JacksonXmlProperty(localName = "PRIORITY")
  @XmlElement(name = "PRIORITY")
  private Integer PRIORITY = null;

  @JsonProperty("PERCENT_COMPLETE")
  @JacksonXmlProperty(localName = "PERCENT_COMPLETE")
  @XmlElement(name = "PERCENT_COMPLETE")
  private Integer PERCENT_COMPLETE = null;

  @JsonProperty("START_DATE")
  @JacksonXmlProperty(localName = "START_DATE")
  @XmlElement(name = "START_DATE")
  private OffsetDateTime START_DATE = null;

  @JsonProperty("ASSIGNED_BY_USER_ID")
  @JacksonXmlProperty(localName = "ASSIGNED_BY_USER_ID")
  @XmlElement(name = "ASSIGNED_BY_USER_ID")
  private Integer ASSIGNED_BY_USER_ID = null;

  @JsonProperty("PARENT_TASK_ID")
  @JacksonXmlProperty(localName = "PARENT_TASK_ID")
  @XmlElement(name = "PARENT_TASK_ID")
  private Long PARENT_TASK_ID = null;

  @JsonProperty("OWNER_VISIBLE")
  @JacksonXmlProperty(localName = "OWNER_VISIBLE")
  @XmlElement(name = "OWNER_VISIBLE")
  private Boolean OWNER_VISIBLE = null;

  @JsonProperty("RESPONSIBLE_USER_ID")
  @JacksonXmlProperty(localName = "RESPONSIBLE_USER_ID")
  @XmlElement(name = "RESPONSIBLE_USER_ID")
  private Integer RESPONSIBLE_USER_ID = null;

  @JsonProperty("ASSIGNED_TEAM_ID")
  @JacksonXmlProperty(localName = "ASSIGNED_TEAM_ID")
  @XmlElement(name = "ASSIGNED_TEAM_ID")
  private Long ASSIGNED_TEAM_ID = null;

  @JsonProperty("ASSIGNED_DATE_UTC")
  @JacksonXmlProperty(localName = "ASSIGNED_DATE_UTC")
  @XmlElement(name = "ASSIGNED_DATE_UTC")
  private OffsetDateTime ASSIGNED_DATE_UTC = null;

  @JsonProperty("OWNER_USER_ID")
  @JacksonXmlProperty(localName = "OWNER_USER_ID")
  @XmlElement(name = "OWNER_USER_ID")
  private Integer OWNER_USER_ID = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("REMINDER_DATE_UTC")
  @JacksonXmlProperty(localName = "REMINDER_DATE_UTC")
  @XmlElement(name = "REMINDER_DATE_UTC")
  private OffsetDateTime REMINDER_DATE_UTC = null;

  @JsonProperty("REMINDER_SENT")
  @JacksonXmlProperty(localName = "REMINDER_SENT")
  @XmlElement(name = "REMINDER_SENT")
  private Boolean REMINDER_SENT = null;

  @JsonProperty("RECURRENCE")
  @JacksonXmlProperty(localName = "RECURRENCE")
  @XmlElement(name = "RECURRENCE")
  private String RECURRENCE = null;

  @JsonProperty("TASKLINKS")
  @JacksonXmlProperty(localName = "TASKLINKS")
  @XmlElement(name = "TASKLINKS")
  private List<TaskLink> TASKLINKS = null;

  @JsonProperty("CAN_EDIT")
  @JacksonXmlProperty(localName = "CAN_EDIT")
  @XmlElement(name = "CAN_EDIT")
  private Boolean CAN_EDIT = null;

  @JsonProperty("CAN_DELETE")
  @JacksonXmlProperty(localName = "CAN_DELETE")
  @XmlElement(name = "CAN_DELETE")
  private Boolean CAN_DELETE = null;

  public Task TASK_ID(Long TASK_ID) {
    this.TASK_ID = TASK_ID;
    return this;
  }

   /**
   * Get TASK_ID
   * @return TASK_ID
  **/
  
  public Long getTASKID() {
    return TASK_ID;
  }

  public void setTASKID(Long TASK_ID) {
    this.TASK_ID = TASK_ID;
  }

  public Task TITLE(String TITLE) {
    this.TITLE = TITLE;
    return this;
  }

   /**
   * Get TITLE
   * @return TITLE
  **/
  
  public String getTITLE() {
    return TITLE;
  }

  public void setTITLE(String TITLE) {
    this.TITLE = TITLE;
  }

  public Task CATEGORY_ID(Long CATEGORY_ID) {
    this.CATEGORY_ID = CATEGORY_ID;
    return this;
  }

   /**
   * Get CATEGORY_ID
   * @return CATEGORY_ID
  **/
  
  public Long getCATEGORYID() {
    return CATEGORY_ID;
  }

  public void setCATEGORYID(Long CATEGORY_ID) {
    this.CATEGORY_ID = CATEGORY_ID;
  }

  public Task DUE_DATE(OffsetDateTime DUE_DATE) {
    this.DUE_DATE = DUE_DATE;
    return this;
  }

   /**
   * Get DUE_DATE
   * @return DUE_DATE
  **/
  
  public OffsetDateTime getDUEDATE() {
    return DUE_DATE;
  }

  public void setDUEDATE(OffsetDateTime DUE_DATE) {
    this.DUE_DATE = DUE_DATE;
  }

  public Task COMPLETED_DATE_UTC(OffsetDateTime COMPLETED_DATE_UTC) {
    this.COMPLETED_DATE_UTC = COMPLETED_DATE_UTC;
    return this;
  }

   /**
   * Get COMPLETED_DATE_UTC
   * @return COMPLETED_DATE_UTC
  **/
  
  public OffsetDateTime getCOMPLETEDDATEUTC() {
    return COMPLETED_DATE_UTC;
  }

  public void setCOMPLETEDDATEUTC(OffsetDateTime COMPLETED_DATE_UTC) {
    this.COMPLETED_DATE_UTC = COMPLETED_DATE_UTC;
  }

  public Task PUBLICLY_VISIBLE(Boolean PUBLICLY_VISIBLE) {
    this.PUBLICLY_VISIBLE = PUBLICLY_VISIBLE;
    return this;
  }

   /**
   * Get PUBLICLY_VISIBLE
   * @return PUBLICLY_VISIBLE
  **/
  
  public Boolean getPUBLICLYVISIBLE() {
    return PUBLICLY_VISIBLE;
  }

  public void setPUBLICLYVISIBLE(Boolean PUBLICLY_VISIBLE) {
    this.PUBLICLY_VISIBLE = PUBLICLY_VISIBLE;
  }

  public Task COMPLETED(Boolean COMPLETED) {
    this.COMPLETED = COMPLETED;
    return this;
  }

   /**
   * Get COMPLETED
   * @return COMPLETED
  **/
  
  public Boolean getCOMPLETED() {
    return COMPLETED;
  }

  public void setCOMPLETED(Boolean COMPLETED) {
    this.COMPLETED = COMPLETED;
  }

  public Task PROJECT_ID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
    return this;
  }

   /**
   * Get PROJECT_ID
   * @return PROJECT_ID
  **/
  
  public Long getPROJECTID() {
    return PROJECT_ID;
  }

  public void setPROJECTID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
  }

  public Task OPPORTUNITY_ID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
    return this;
  }

   /**
   * Get OPPORTUNITY_ID
   * @return OPPORTUNITY_ID
  **/
  
  public Long getOPPORTUNITYID() {
    return OPPORTUNITY_ID;
  }

  public void setOPPORTUNITYID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
  }

  public Task MILESTONE_ID(Long MILESTONE_ID) {
    this.MILESTONE_ID = MILESTONE_ID;
    return this;
  }

   /**
   * Get MILESTONE_ID
   * @return MILESTONE_ID
  **/
  
  public Long getMILESTONEID() {
    return MILESTONE_ID;
  }

  public void setMILESTONEID(Long MILESTONE_ID) {
    this.MILESTONE_ID = MILESTONE_ID;
  }

  public Task PIPELINE_ID(Long PIPELINE_ID) {
    this.PIPELINE_ID = PIPELINE_ID;
    return this;
  }

   /**
   * Get PIPELINE_ID
   * @return PIPELINE_ID
  **/
  
  public Long getPIPELINEID() {
    return PIPELINE_ID;
  }

  public void setPIPELINEID(Long PIPELINE_ID) {
    this.PIPELINE_ID = PIPELINE_ID;
  }

  public Task STAGE_ID(Long STAGE_ID) {
    this.STAGE_ID = STAGE_ID;
    return this;
  }

   /**
   * Get STAGE_ID
   * @return STAGE_ID
  **/
  
  public Long getSTAGEID() {
    return STAGE_ID;
  }

  public void setSTAGEID(Long STAGE_ID) {
    this.STAGE_ID = STAGE_ID;
  }

  public Task DETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
    return this;
  }

   /**
   * Get DETAILS
   * @return DETAILS
  **/
  
  public String getDETAILS() {
    return DETAILS;
  }

  public void setDETAILS(String DETAILS) {
    this.DETAILS = DETAILS;
  }

  public Task STATUS(String STATUS) {
    this.STATUS = STATUS;
    return this;
  }

   /**
   * Get STATUS
   * @return STATUS
  **/
  
  public String getSTATUS() {
    return STATUS;
  }

  public void setSTATUS(String STATUS) {
    this.STATUS = STATUS;
  }

  public Task PRIORITY(Integer PRIORITY) {
    this.PRIORITY = PRIORITY;
    return this;
  }

   /**
   * Get PRIORITY
   * @return PRIORITY
  **/
  
  public Integer getPRIORITY() {
    return PRIORITY;
  }

  public void setPRIORITY(Integer PRIORITY) {
    this.PRIORITY = PRIORITY;
  }

  public Task PERCENT_COMPLETE(Integer PERCENT_COMPLETE) {
    this.PERCENT_COMPLETE = PERCENT_COMPLETE;
    return this;
  }

   /**
   * Get PERCENT_COMPLETE
   * @return PERCENT_COMPLETE
  **/
  
  public Integer getPERCENTCOMPLETE() {
    return PERCENT_COMPLETE;
  }

  public void setPERCENTCOMPLETE(Integer PERCENT_COMPLETE) {
    this.PERCENT_COMPLETE = PERCENT_COMPLETE;
  }

  public Task START_DATE(OffsetDateTime START_DATE) {
    this.START_DATE = START_DATE;
    return this;
  }

   /**
   * Get START_DATE
   * @return START_DATE
  **/
  
  public OffsetDateTime getSTARTDATE() {
    return START_DATE;
  }

  public void setSTARTDATE(OffsetDateTime START_DATE) {
    this.START_DATE = START_DATE;
  }

  public Task ASSIGNED_BY_USER_ID(Integer ASSIGNED_BY_USER_ID) {
    this.ASSIGNED_BY_USER_ID = ASSIGNED_BY_USER_ID;
    return this;
  }

   /**
   * Get ASSIGNED_BY_USER_ID
   * @return ASSIGNED_BY_USER_ID
  **/
  
  public Integer getASSIGNEDBYUSERID() {
    return ASSIGNED_BY_USER_ID;
  }

  public void setASSIGNEDBYUSERID(Integer ASSIGNED_BY_USER_ID) {
    this.ASSIGNED_BY_USER_ID = ASSIGNED_BY_USER_ID;
  }

  public Task PARENT_TASK_ID(Long PARENT_TASK_ID) {
    this.PARENT_TASK_ID = PARENT_TASK_ID;
    return this;
  }

   /**
   * Get PARENT_TASK_ID
   * @return PARENT_TASK_ID
  **/
  
  public Long getPARENTTASKID() {
    return PARENT_TASK_ID;
  }

  public void setPARENTTASKID(Long PARENT_TASK_ID) {
    this.PARENT_TASK_ID = PARENT_TASK_ID;
  }

  public Task OWNER_VISIBLE(Boolean OWNER_VISIBLE) {
    this.OWNER_VISIBLE = OWNER_VISIBLE;
    return this;
  }

   /**
   * Get OWNER_VISIBLE
   * @return OWNER_VISIBLE
  **/
  
  public Boolean getOWNERVISIBLE() {
    return OWNER_VISIBLE;
  }

  public void setOWNERVISIBLE(Boolean OWNER_VISIBLE) {
    this.OWNER_VISIBLE = OWNER_VISIBLE;
  }

  public Task RESPONSIBLE_USER_ID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
    return this;
  }

   /**
   * Get RESPONSIBLE_USER_ID
   * @return RESPONSIBLE_USER_ID
  **/
  
  public Integer getRESPONSIBLEUSERID() {
    return RESPONSIBLE_USER_ID;
  }

  public void setRESPONSIBLEUSERID(Integer RESPONSIBLE_USER_ID) {
    this.RESPONSIBLE_USER_ID = RESPONSIBLE_USER_ID;
  }

  public Task ASSIGNED_TEAM_ID(Long ASSIGNED_TEAM_ID) {
    this.ASSIGNED_TEAM_ID = ASSIGNED_TEAM_ID;
    return this;
  }

   /**
   * Get ASSIGNED_TEAM_ID
   * @return ASSIGNED_TEAM_ID
  **/
  
  public Long getASSIGNEDTEAMID() {
    return ASSIGNED_TEAM_ID;
  }

  public void setASSIGNEDTEAMID(Long ASSIGNED_TEAM_ID) {
    this.ASSIGNED_TEAM_ID = ASSIGNED_TEAM_ID;
  }

  public Task ASSIGNED_DATE_UTC(OffsetDateTime ASSIGNED_DATE_UTC) {
    this.ASSIGNED_DATE_UTC = ASSIGNED_DATE_UTC;
    return this;
  }

   /**
   * Get ASSIGNED_DATE_UTC
   * @return ASSIGNED_DATE_UTC
  **/
  
  public OffsetDateTime getASSIGNEDDATEUTC() {
    return ASSIGNED_DATE_UTC;
  }

  public void setASSIGNEDDATEUTC(OffsetDateTime ASSIGNED_DATE_UTC) {
    this.ASSIGNED_DATE_UTC = ASSIGNED_DATE_UTC;
  }

  public Task OWNER_USER_ID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
    return this;
  }

   /**
   * Get OWNER_USER_ID
   * @return OWNER_USER_ID
  **/
  
  public Integer getOWNERUSERID() {
    return OWNER_USER_ID;
  }

  public void setOWNERUSERID(Integer OWNER_USER_ID) {
    this.OWNER_USER_ID = OWNER_USER_ID;
  }

  public Task DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public Task DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public Task REMINDER_DATE_UTC(OffsetDateTime REMINDER_DATE_UTC) {
    this.REMINDER_DATE_UTC = REMINDER_DATE_UTC;
    return this;
  }

   /**
   * Get REMINDER_DATE_UTC
   * @return REMINDER_DATE_UTC
  **/
  
  public OffsetDateTime getREMINDERDATEUTC() {
    return REMINDER_DATE_UTC;
  }

  public void setREMINDERDATEUTC(OffsetDateTime REMINDER_DATE_UTC) {
    this.REMINDER_DATE_UTC = REMINDER_DATE_UTC;
  }

  public Task REMINDER_SENT(Boolean REMINDER_SENT) {
    this.REMINDER_SENT = REMINDER_SENT;
    return this;
  }

   /**
   * Get REMINDER_SENT
   * @return REMINDER_SENT
  **/
  
  public Boolean getREMINDERSENT() {
    return REMINDER_SENT;
  }

  public void setREMINDERSENT(Boolean REMINDER_SENT) {
    this.REMINDER_SENT = REMINDER_SENT;
  }

  public Task RECURRENCE(String RECURRENCE) {
    this.RECURRENCE = RECURRENCE;
    return this;
  }

   /**
   * Get RECURRENCE
   * @return RECURRENCE
  **/
  
  public String getRECURRENCE() {
    return RECURRENCE;
  }

  public void setRECURRENCE(String RECURRENCE) {
    this.RECURRENCE = RECURRENCE;
  }

  public Task TASKLINKS(List<TaskLink> TASKLINKS) {
    this.TASKLINKS = TASKLINKS;
    return this;
  }

  public Task addTASKLINKSItem(TaskLink TASKLINKSItem) {
    if (this.TASKLINKS == null) {
      this.TASKLINKS = new ArrayList<TaskLink>();
    }
    this.TASKLINKS.add(TASKLINKSItem);
    return this;
  }

   /**
   * Get TASKLINKS
   * @return TASKLINKS
  **/
  
  public List<TaskLink> getTASKLINKS() {
    return TASKLINKS;
  }

  public void setTASKLINKS(List<TaskLink> TASKLINKS) {
    this.TASKLINKS = TASKLINKS;
  }

  public Task CAN_EDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
    return this;
  }

   /**
   * Get CAN_EDIT
   * @return CAN_EDIT
  **/
  
  public Boolean getCANEDIT() {
    return CAN_EDIT;
  }

  public void setCANEDIT(Boolean CAN_EDIT) {
    this.CAN_EDIT = CAN_EDIT;
  }

  public Task CAN_DELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
    return this;
  }

   /**
   * Get CAN_DELETE
   * @return CAN_DELETE
  **/
  
  public Boolean getCANDELETE() {
    return CAN_DELETE;
  }

  public void setCANDELETE(Boolean CAN_DELETE) {
    this.CAN_DELETE = CAN_DELETE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.TASK_ID, task.TASK_ID) &&
        Objects.equals(this.TITLE, task.TITLE) &&
        Objects.equals(this.CATEGORY_ID, task.CATEGORY_ID) &&
        Objects.equals(this.DUE_DATE, task.DUE_DATE) &&
        Objects.equals(this.COMPLETED_DATE_UTC, task.COMPLETED_DATE_UTC) &&
        Objects.equals(this.PUBLICLY_VISIBLE, task.PUBLICLY_VISIBLE) &&
        Objects.equals(this.COMPLETED, task.COMPLETED) &&
        Objects.equals(this.PROJECT_ID, task.PROJECT_ID) &&
        Objects.equals(this.OPPORTUNITY_ID, task.OPPORTUNITY_ID) &&
        Objects.equals(this.MILESTONE_ID, task.MILESTONE_ID) &&
        Objects.equals(this.PIPELINE_ID, task.PIPELINE_ID) &&
        Objects.equals(this.STAGE_ID, task.STAGE_ID) &&
        Objects.equals(this.DETAILS, task.DETAILS) &&
        Objects.equals(this.STATUS, task.STATUS) &&
        Objects.equals(this.PRIORITY, task.PRIORITY) &&
        Objects.equals(this.PERCENT_COMPLETE, task.PERCENT_COMPLETE) &&
        Objects.equals(this.START_DATE, task.START_DATE) &&
        Objects.equals(this.ASSIGNED_BY_USER_ID, task.ASSIGNED_BY_USER_ID) &&
        Objects.equals(this.PARENT_TASK_ID, task.PARENT_TASK_ID) &&
        Objects.equals(this.OWNER_VISIBLE, task.OWNER_VISIBLE) &&
        Objects.equals(this.RESPONSIBLE_USER_ID, task.RESPONSIBLE_USER_ID) &&
        Objects.equals(this.ASSIGNED_TEAM_ID, task.ASSIGNED_TEAM_ID) &&
        Objects.equals(this.ASSIGNED_DATE_UTC, task.ASSIGNED_DATE_UTC) &&
        Objects.equals(this.OWNER_USER_ID, task.OWNER_USER_ID) &&
        Objects.equals(this.DATE_CREATED_UTC, task.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, task.DATE_UPDATED_UTC) &&
        Objects.equals(this.REMINDER_DATE_UTC, task.REMINDER_DATE_UTC) &&
        Objects.equals(this.REMINDER_SENT, task.REMINDER_SENT) &&
        Objects.equals(this.RECURRENCE, task.RECURRENCE) &&
        Objects.equals(this.TASKLINKS, task.TASKLINKS) &&
        Objects.equals(this.CAN_EDIT, task.CAN_EDIT) &&
        Objects.equals(this.CAN_DELETE, task.CAN_DELETE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TASK_ID, TITLE, CATEGORY_ID, DUE_DATE, COMPLETED_DATE_UTC, PUBLICLY_VISIBLE, COMPLETED, PROJECT_ID, OPPORTUNITY_ID, MILESTONE_ID, PIPELINE_ID, STAGE_ID, DETAILS, STATUS, PRIORITY, PERCENT_COMPLETE, START_DATE, ASSIGNED_BY_USER_ID, PARENT_TASK_ID, OWNER_VISIBLE, RESPONSIBLE_USER_ID, ASSIGNED_TEAM_ID, ASSIGNED_DATE_UTC, OWNER_USER_ID, DATE_CREATED_UTC, DATE_UPDATED_UTC, REMINDER_DATE_UTC, REMINDER_SENT, RECURRENCE, TASKLINKS, CAN_EDIT, CAN_DELETE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    
    sb.append("    TASK_ID: ").append(toIndentedString(TASK_ID)).append("\n");
    sb.append("    TITLE: ").append(toIndentedString(TITLE)).append("\n");
    sb.append("    CATEGORY_ID: ").append(toIndentedString(CATEGORY_ID)).append("\n");
    sb.append("    DUE_DATE: ").append(toIndentedString(DUE_DATE)).append("\n");
    sb.append("    COMPLETED_DATE_UTC: ").append(toIndentedString(COMPLETED_DATE_UTC)).append("\n");
    sb.append("    PUBLICLY_VISIBLE: ").append(toIndentedString(PUBLICLY_VISIBLE)).append("\n");
    sb.append("    COMPLETED: ").append(toIndentedString(COMPLETED)).append("\n");
    sb.append("    PROJECT_ID: ").append(toIndentedString(PROJECT_ID)).append("\n");
    sb.append("    OPPORTUNITY_ID: ").append(toIndentedString(OPPORTUNITY_ID)).append("\n");
    sb.append("    MILESTONE_ID: ").append(toIndentedString(MILESTONE_ID)).append("\n");
    sb.append("    PIPELINE_ID: ").append(toIndentedString(PIPELINE_ID)).append("\n");
    sb.append("    STAGE_ID: ").append(toIndentedString(STAGE_ID)).append("\n");
    sb.append("    DETAILS: ").append(toIndentedString(DETAILS)).append("\n");
    sb.append("    STATUS: ").append(toIndentedString(STATUS)).append("\n");
    sb.append("    PRIORITY: ").append(toIndentedString(PRIORITY)).append("\n");
    sb.append("    PERCENT_COMPLETE: ").append(toIndentedString(PERCENT_COMPLETE)).append("\n");
    sb.append("    START_DATE: ").append(toIndentedString(START_DATE)).append("\n");
    sb.append("    ASSIGNED_BY_USER_ID: ").append(toIndentedString(ASSIGNED_BY_USER_ID)).append("\n");
    sb.append("    PARENT_TASK_ID: ").append(toIndentedString(PARENT_TASK_ID)).append("\n");
    sb.append("    OWNER_VISIBLE: ").append(toIndentedString(OWNER_VISIBLE)).append("\n");
    sb.append("    RESPONSIBLE_USER_ID: ").append(toIndentedString(RESPONSIBLE_USER_ID)).append("\n");
    sb.append("    ASSIGNED_TEAM_ID: ").append(toIndentedString(ASSIGNED_TEAM_ID)).append("\n");
    sb.append("    ASSIGNED_DATE_UTC: ").append(toIndentedString(ASSIGNED_DATE_UTC)).append("\n");
    sb.append("    OWNER_USER_ID: ").append(toIndentedString(OWNER_USER_ID)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    REMINDER_DATE_UTC: ").append(toIndentedString(REMINDER_DATE_UTC)).append("\n");
    sb.append("    REMINDER_SENT: ").append(toIndentedString(REMINDER_SENT)).append("\n");
    sb.append("    RECURRENCE: ").append(toIndentedString(RECURRENCE)).append("\n");
    sb.append("    TASKLINKS: ").append(toIndentedString(TASKLINKS)).append("\n");
    sb.append("    CAN_EDIT: ").append(toIndentedString(CAN_EDIT)).append("\n");
    sb.append("    CAN_DELETE: ").append(toIndentedString(CAN_DELETE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

