/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * TaskLink
 */
@JacksonXmlRootElement(localName = "TaskLink")
@XmlRootElement(name = "TaskLink")
@XmlAccessorType(XmlAccessType.FIELD)
public class TaskLink implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("TASK_LINK_ID")
  @JacksonXmlProperty(localName = "TASK_LINK_ID")
  @XmlElement(name = "TASK_LINK_ID")
  private Long TASK_LINK_ID = null;

  @JsonProperty("TASK_ID")
  @JacksonXmlProperty(localName = "TASK_ID")
  @XmlElement(name = "TASK_ID")
  private Long TASK_ID = null;

  @JsonProperty("CONTACT_ID")
  @JacksonXmlProperty(localName = "CONTACT_ID")
  @XmlElement(name = "CONTACT_ID")
  private Long CONTACT_ID = null;

  @JsonProperty("ORGANISATION_ID")
  @JacksonXmlProperty(localName = "ORGANISATION_ID")
  @XmlElement(name = "ORGANISATION_ID")
  private Long ORGANISATION_ID = null;

  @JsonProperty("OPPORTUNITY_ID")
  @JacksonXmlProperty(localName = "OPPORTUNITY_ID")
  @XmlElement(name = "OPPORTUNITY_ID")
  private Long OPPORTUNITY_ID = null;

  @JsonProperty("PROJECT_ID")
  @JacksonXmlProperty(localName = "PROJECT_ID")
  @XmlElement(name = "PROJECT_ID")
  private Long PROJECT_ID = null;

  @JsonProperty("LEAD_ID")
  @JacksonXmlProperty(localName = "LEAD_ID")
  @XmlElement(name = "LEAD_ID")
  private Long LEAD_ID = null;

  public TaskLink TASK_LINK_ID(Long TASK_LINK_ID) {
    this.TASK_LINK_ID = TASK_LINK_ID;
    return this;
  }

   /**
   * Get TASK_LINK_ID
   * @return TASK_LINK_ID
  **/
  
  public Long getTASKLINKID() {
    return TASK_LINK_ID;
  }

  public void setTASKLINKID(Long TASK_LINK_ID) {
    this.TASK_LINK_ID = TASK_LINK_ID;
  }

  public TaskLink TASK_ID(Long TASK_ID) {
    this.TASK_ID = TASK_ID;
    return this;
  }

   /**
   * Get TASK_ID
   * @return TASK_ID
  **/
  
  public Long getTASKID() {
    return TASK_ID;
  }

  public void setTASKID(Long TASK_ID) {
    this.TASK_ID = TASK_ID;
  }

  public TaskLink CONTACT_ID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
    return this;
  }

   /**
   * Get CONTACT_ID
   * @return CONTACT_ID
  **/
  
  public Long getCONTACTID() {
    return CONTACT_ID;
  }

  public void setCONTACTID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
  }

  public TaskLink ORGANISATION_ID(Long ORGANISATION_ID) {
    this.ORGANISATION_ID = ORGANISATION_ID;
    return this;
  }

   /**
   * Get ORGANISATION_ID
   * @return ORGANISATION_ID
  **/
  
  public Long getORGANISATIONID() {
    return ORGANISATION_ID;
  }

  public void setORGANISATIONID(Long ORGANISATION_ID) {
    this.ORGANISATION_ID = ORGANISATION_ID;
  }

  public TaskLink OPPORTUNITY_ID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
    return this;
  }

   /**
   * Get OPPORTUNITY_ID
   * @return OPPORTUNITY_ID
  **/
  
  public Long getOPPORTUNITYID() {
    return OPPORTUNITY_ID;
  }

  public void setOPPORTUNITYID(Long OPPORTUNITY_ID) {
    this.OPPORTUNITY_ID = OPPORTUNITY_ID;
  }

  public TaskLink PROJECT_ID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
    return this;
  }

   /**
   * Get PROJECT_ID
   * @return PROJECT_ID
  **/
  
  public Long getPROJECTID() {
    return PROJECT_ID;
  }

  public void setPROJECTID(Long PROJECT_ID) {
    this.PROJECT_ID = PROJECT_ID;
  }

  public TaskLink LEAD_ID(Long LEAD_ID) {
    this.LEAD_ID = LEAD_ID;
    return this;
  }

   /**
   * Get LEAD_ID
   * @return LEAD_ID
  **/
  
  public Long getLEADID() {
    return LEAD_ID;
  }

  public void setLEADID(Long LEAD_ID) {
    this.LEAD_ID = LEAD_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskLink taskLink = (TaskLink) o;
    return Objects.equals(this.TASK_LINK_ID, taskLink.TASK_LINK_ID) &&
        Objects.equals(this.TASK_ID, taskLink.TASK_ID) &&
        Objects.equals(this.CONTACT_ID, taskLink.CONTACT_ID) &&
        Objects.equals(this.ORGANISATION_ID, taskLink.ORGANISATION_ID) &&
        Objects.equals(this.OPPORTUNITY_ID, taskLink.OPPORTUNITY_ID) &&
        Objects.equals(this.PROJECT_ID, taskLink.PROJECT_ID) &&
        Objects.equals(this.LEAD_ID, taskLink.LEAD_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TASK_LINK_ID, TASK_ID, CONTACT_ID, ORGANISATION_ID, OPPORTUNITY_ID, PROJECT_ID, LEAD_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskLink {\n");
    
    sb.append("    TASK_LINK_ID: ").append(toIndentedString(TASK_LINK_ID)).append("\n");
    sb.append("    TASK_ID: ").append(toIndentedString(TASK_ID)).append("\n");
    sb.append("    CONTACT_ID: ").append(toIndentedString(CONTACT_ID)).append("\n");
    sb.append("    ORGANISATION_ID: ").append(toIndentedString(ORGANISATION_ID)).append("\n");
    sb.append("    OPPORTUNITY_ID: ").append(toIndentedString(OPPORTUNITY_ID)).append("\n");
    sb.append("    PROJECT_ID: ").append(toIndentedString(PROJECT_ID)).append("\n");
    sb.append("    LEAD_ID: ").append(toIndentedString(LEAD_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

