/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * TeamMember
 */
@JacksonXmlRootElement(localName = "TeamMember")
@XmlRootElement(name = "TeamMember")
@XmlAccessorType(XmlAccessType.FIELD)
public class TeamMember implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("PERMISSION_ID")
  @JacksonXmlProperty(localName = "PERMISSION_ID")
  @XmlElement(name = "PERMISSION_ID")
  private Long PERMISSION_ID = null;

  @JsonProperty("TEAM_ID")
  @JacksonXmlProperty(localName = "TEAM_ID")
  @XmlElement(name = "TEAM_ID")
  private Long TEAM_ID = null;

  @JsonProperty("MEMBER_USER_ID")
  @JacksonXmlProperty(localName = "MEMBER_USER_ID")
  @XmlElement(name = "MEMBER_USER_ID")
  private Integer MEMBER_USER_ID = null;

  public TeamMember PERMISSION_ID(Long PERMISSION_ID) {
    this.PERMISSION_ID = PERMISSION_ID;
    return this;
  }

   /**
   * Get PERMISSION_ID
   * @return PERMISSION_ID
  **/
  
  public Long getPERMISSIONID() {
    return PERMISSION_ID;
  }

  public void setPERMISSIONID(Long PERMISSION_ID) {
    this.PERMISSION_ID = PERMISSION_ID;
  }

  public TeamMember TEAM_ID(Long TEAM_ID) {
    this.TEAM_ID = TEAM_ID;
    return this;
  }

   /**
   * Get TEAM_ID
   * @return TEAM_ID
  **/
  
  public Long getTEAMID() {
    return TEAM_ID;
  }

  public void setTEAMID(Long TEAM_ID) {
    this.TEAM_ID = TEAM_ID;
  }

  public TeamMember MEMBER_USER_ID(Integer MEMBER_USER_ID) {
    this.MEMBER_USER_ID = MEMBER_USER_ID;
    return this;
  }

   /**
   * Get MEMBER_USER_ID
   * @return MEMBER_USER_ID
  **/
  
  public Integer getMEMBERUSERID() {
    return MEMBER_USER_ID;
  }

  public void setMEMBERUSERID(Integer MEMBER_USER_ID) {
    this.MEMBER_USER_ID = MEMBER_USER_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamMember teamMember = (TeamMember) o;
    return Objects.equals(this.PERMISSION_ID, teamMember.PERMISSION_ID) &&
        Objects.equals(this.TEAM_ID, teamMember.TEAM_ID) &&
        Objects.equals(this.MEMBER_USER_ID, teamMember.MEMBER_USER_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(PERMISSION_ID, TEAM_ID, MEMBER_USER_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamMember {\n");
    
    sb.append("    PERMISSION_ID: ").append(toIndentedString(PERMISSION_ID)).append("\n");
    sb.append("    TEAM_ID: ").append(toIndentedString(TEAM_ID)).append("\n");
    sb.append("    MEMBER_USER_ID: ").append(toIndentedString(MEMBER_USER_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

