/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.insightly.model.TeamMember;


import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * Team
 */
@JacksonXmlRootElement(localName = "Team")
@XmlRootElement(name = "Team")
@XmlAccessorType(XmlAccessType.FIELD)
public class Team implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("TEAM_ID")
  @JacksonXmlProperty(localName = "TEAM_ID")
  @XmlElement(name = "TEAM_ID")
  private Long TEAM_ID = null;

  @JsonProperty("TEAM_NAME")
  @JacksonXmlProperty(localName = "TEAM_NAME")
  @XmlElement(name = "TEAM_NAME")
  private String TEAM_NAME = null;

  @JsonProperty("ANONYMOUS_TEAM")
  @JacksonXmlProperty(localName = "ANONYMOUS_TEAM")
  @XmlElement(name = "ANONYMOUS_TEAM")
  private Boolean ANONYMOUS_TEAM = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("TEAMMEMBERS")
  @JacksonXmlProperty(localName = "TEAMMEMBERS")
  @XmlElement(name = "TEAMMEMBERS")
  private List<TeamMember> TEAMMEMBERS = null;

  public Team TEAM_ID(Long TEAM_ID) {
    this.TEAM_ID = TEAM_ID;
    return this;
  }

   /**
   * Get TEAM_ID
   * @return TEAM_ID
  **/
  
  public Long getTEAMID() {
    return TEAM_ID;
  }

  public void setTEAMID(Long TEAM_ID) {
    this.TEAM_ID = TEAM_ID;
  }

  public Team TEAM_NAME(String TEAM_NAME) {
    this.TEAM_NAME = TEAM_NAME;
    return this;
  }

   /**
   * Get TEAM_NAME
   * @return TEAM_NAME
  **/
  
  public String getTEAMNAME() {
    return TEAM_NAME;
  }

  public void setTEAMNAME(String TEAM_NAME) {
    this.TEAM_NAME = TEAM_NAME;
  }

  public Team ANONYMOUS_TEAM(Boolean ANONYMOUS_TEAM) {
    this.ANONYMOUS_TEAM = ANONYMOUS_TEAM;
    return this;
  }

   /**
   * Get ANONYMOUS_TEAM
   * @return ANONYMOUS_TEAM
  **/
  
  public Boolean getANONYMOUSTEAM() {
    return ANONYMOUS_TEAM;
  }

  public void setANONYMOUSTEAM(Boolean ANONYMOUS_TEAM) {
    this.ANONYMOUS_TEAM = ANONYMOUS_TEAM;
  }

  public Team DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public Team DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public Team TEAMMEMBERS(List<TeamMember> TEAMMEMBERS) {
    this.TEAMMEMBERS = TEAMMEMBERS;
    return this;
  }

  public Team addTEAMMEMBERSItem(TeamMember TEAMMEMBERSItem) {
    if (this.TEAMMEMBERS == null) {
      this.TEAMMEMBERS = new ArrayList<TeamMember>();
    }
    this.TEAMMEMBERS.add(TEAMMEMBERSItem);
    return this;
  }

   /**
   * Get TEAMMEMBERS
   * @return TEAMMEMBERS
  **/
  
  public List<TeamMember> getTEAMMEMBERS() {
    return TEAMMEMBERS;
  }

  public void setTEAMMEMBERS(List<TeamMember> TEAMMEMBERS) {
    this.TEAMMEMBERS = TEAMMEMBERS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Team team = (Team) o;
    return Objects.equals(this.TEAM_ID, team.TEAM_ID) &&
        Objects.equals(this.TEAM_NAME, team.TEAM_NAME) &&
        Objects.equals(this.ANONYMOUS_TEAM, team.ANONYMOUS_TEAM) &&
        Objects.equals(this.DATE_CREATED_UTC, team.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, team.DATE_UPDATED_UTC) &&
        Objects.equals(this.TEAMMEMBERS, team.TEAMMEMBERS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TEAM_ID, TEAM_NAME, ANONYMOUS_TEAM, DATE_CREATED_UTC, DATE_UPDATED_UTC, TEAMMEMBERS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Team {\n");
    
    sb.append("    TEAM_ID: ").append(toIndentedString(TEAM_ID)).append("\n");
    sb.append("    TEAM_NAME: ").append(toIndentedString(TEAM_NAME)).append("\n");
    sb.append("    ANONYMOUS_TEAM: ").append(toIndentedString(ANONYMOUS_TEAM)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    TEAMMEMBERS: ").append(toIndentedString(TEAMMEMBERS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

