/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * User
 */
@JacksonXmlRootElement(localName = "User")
@XmlRootElement(name = "User")
@XmlAccessorType(XmlAccessType.FIELD)
public class User implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("USER_ID")
  @JacksonXmlProperty(localName = "USER_ID")
  @XmlElement(name = "USER_ID")
  private Long USER_ID = null;

  @JsonProperty("CONTACT_ID")
  @JacksonXmlProperty(localName = "CONTACT_ID")
  @XmlElement(name = "CONTACT_ID")
  private Long CONTACT_ID = null;

  @JsonProperty("FIRST_NAME")
  @JacksonXmlProperty(localName = "FIRST_NAME")
  @XmlElement(name = "FIRST_NAME")
  private String FIRST_NAME = null;

  @JsonProperty("LAST_NAME")
  @JacksonXmlProperty(localName = "LAST_NAME")
  @XmlElement(name = "LAST_NAME")
  private String LAST_NAME = null;

  @JsonProperty("TIMEZONE_ID")
  @JacksonXmlProperty(localName = "TIMEZONE_ID")
  @XmlElement(name = "TIMEZONE_ID")
  private String TIMEZONE_ID = null;

  @JsonProperty("EMAIL_ADDRESS")
  @JacksonXmlProperty(localName = "EMAIL_ADDRESS")
  @XmlElement(name = "EMAIL_ADDRESS")
  private String EMAIL_ADDRESS = null;

  @JsonProperty("EMAIL_DROPBOX_IDENTIFIER")
  @JacksonXmlProperty(localName = "EMAIL_DROPBOX_IDENTIFIER")
  @XmlElement(name = "EMAIL_DROPBOX_IDENTIFIER")
  private String EMAIL_DROPBOX_IDENTIFIER = null;

  @JsonProperty("EMAIL_DROPBOX_ADDRESS")
  @JacksonXmlProperty(localName = "EMAIL_DROPBOX_ADDRESS")
  @XmlElement(name = "EMAIL_DROPBOX_ADDRESS")
  private String EMAIL_DROPBOX_ADDRESS = null;

  @JsonProperty("ADMINISTRATOR")
  @JacksonXmlProperty(localName = "ADMINISTRATOR")
  @XmlElement(name = "ADMINISTRATOR")
  private Boolean ADMINISTRATOR = null;

  @JsonProperty("ACCOUNT_OWNER")
  @JacksonXmlProperty(localName = "ACCOUNT_OWNER")
  @XmlElement(name = "ACCOUNT_OWNER")
  private Boolean ACCOUNT_OWNER = null;

  @JsonProperty("ACTIVE")
  @JacksonXmlProperty(localName = "ACTIVE")
  @XmlElement(name = "ACTIVE")
  private Boolean ACTIVE = null;

  @JsonProperty("DATE_CREATED_UTC")
  @JacksonXmlProperty(localName = "DATE_CREATED_UTC")
  @XmlElement(name = "DATE_CREATED_UTC")
  private OffsetDateTime DATE_CREATED_UTC = null;

  @JsonProperty("DATE_UPDATED_UTC")
  @JacksonXmlProperty(localName = "DATE_UPDATED_UTC")
  @XmlElement(name = "DATE_UPDATED_UTC")
  private OffsetDateTime DATE_UPDATED_UTC = null;

  @JsonProperty("USER_CURRENCY")
  @JacksonXmlProperty(localName = "USER_CURRENCY")
  @XmlElement(name = "USER_CURRENCY")
  private String USER_CURRENCY = null;

  @JsonProperty("CONTACT_DISPLAY")
  @JacksonXmlProperty(localName = "CONTACT_DISPLAY")
  @XmlElement(name = "CONTACT_DISPLAY")
  private String CONTACT_DISPLAY = null;

  @JsonProperty("CONTACT_ORDER")
  @JacksonXmlProperty(localName = "CONTACT_ORDER")
  @XmlElement(name = "CONTACT_ORDER")
  private String CONTACT_ORDER = null;

  @JsonProperty("TASK_WEEK_START")
  @JacksonXmlProperty(localName = "TASK_WEEK_START")
  @XmlElement(name = "TASK_WEEK_START")
  private Integer TASK_WEEK_START = null;

  @JsonProperty("INSTANCE_ID")
  @JacksonXmlProperty(localName = "INSTANCE_ID")
  @XmlElement(name = "INSTANCE_ID")
  private Long INSTANCE_ID = null;

  public User USER_ID(Long USER_ID) {
    this.USER_ID = USER_ID;
    return this;
  }

   /**
   * Get USER_ID
   * @return USER_ID
  **/
  
  public Long getUSERID() {
    return USER_ID;
  }

  public void setUSERID(Long USER_ID) {
    this.USER_ID = USER_ID;
  }

  public User CONTACT_ID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
    return this;
  }

   /**
   * Get CONTACT_ID
   * @return CONTACT_ID
  **/
  
  public Long getCONTACTID() {
    return CONTACT_ID;
  }

  public void setCONTACTID(Long CONTACT_ID) {
    this.CONTACT_ID = CONTACT_ID;
  }

  public User FIRST_NAME(String FIRST_NAME) {
    this.FIRST_NAME = FIRST_NAME;
    return this;
  }

   /**
   * Get FIRST_NAME
   * @return FIRST_NAME
  **/
  
  public String getFIRSTNAME() {
    return FIRST_NAME;
  }

  public void setFIRSTNAME(String FIRST_NAME) {
    this.FIRST_NAME = FIRST_NAME;
  }

  public User LAST_NAME(String LAST_NAME) {
    this.LAST_NAME = LAST_NAME;
    return this;
  }

   /**
   * Get LAST_NAME
   * @return LAST_NAME
  **/
  
  public String getLASTNAME() {
    return LAST_NAME;
  }

  public void setLASTNAME(String LAST_NAME) {
    this.LAST_NAME = LAST_NAME;
  }

  public User TIMEZONE_ID(String TIMEZONE_ID) {
    this.TIMEZONE_ID = TIMEZONE_ID;
    return this;
  }

   /**
   * Get TIMEZONE_ID
   * @return TIMEZONE_ID
  **/
  
  public String getTIMEZONEID() {
    return TIMEZONE_ID;
  }

  public void setTIMEZONEID(String TIMEZONE_ID) {
    this.TIMEZONE_ID = TIMEZONE_ID;
  }

  public User EMAIL_ADDRESS(String EMAIL_ADDRESS) {
    this.EMAIL_ADDRESS = EMAIL_ADDRESS;
    return this;
  }

   /**
   * Get EMAIL_ADDRESS
   * @return EMAIL_ADDRESS
  **/
  
  public String getEMAILADDRESS() {
    return EMAIL_ADDRESS;
  }

  public void setEMAILADDRESS(String EMAIL_ADDRESS) {
    this.EMAIL_ADDRESS = EMAIL_ADDRESS;
  }

  public User EMAIL_DROPBOX_IDENTIFIER(String EMAIL_DROPBOX_IDENTIFIER) {
    this.EMAIL_DROPBOX_IDENTIFIER = EMAIL_DROPBOX_IDENTIFIER;
    return this;
  }

   /**
   * Get EMAIL_DROPBOX_IDENTIFIER
   * @return EMAIL_DROPBOX_IDENTIFIER
  **/
  
  public String getEMAILDROPBOXIDENTIFIER() {
    return EMAIL_DROPBOX_IDENTIFIER;
  }

  public void setEMAILDROPBOXIDENTIFIER(String EMAIL_DROPBOX_IDENTIFIER) {
    this.EMAIL_DROPBOX_IDENTIFIER = EMAIL_DROPBOX_IDENTIFIER;
  }

  public User EMAIL_DROPBOX_ADDRESS(String EMAIL_DROPBOX_ADDRESS) {
    this.EMAIL_DROPBOX_ADDRESS = EMAIL_DROPBOX_ADDRESS;
    return this;
  }

   /**
   * Get EMAIL_DROPBOX_ADDRESS
   * @return EMAIL_DROPBOX_ADDRESS
  **/
  
  public String getEMAILDROPBOXADDRESS() {
    return EMAIL_DROPBOX_ADDRESS;
  }

  public void setEMAILDROPBOXADDRESS(String EMAIL_DROPBOX_ADDRESS) {
    this.EMAIL_DROPBOX_ADDRESS = EMAIL_DROPBOX_ADDRESS;
  }

  public User ADMINISTRATOR(Boolean ADMINISTRATOR) {
    this.ADMINISTRATOR = ADMINISTRATOR;
    return this;
  }

   /**
   * Get ADMINISTRATOR
   * @return ADMINISTRATOR
  **/
  
  public Boolean getADMINISTRATOR() {
    return ADMINISTRATOR;
  }

  public void setADMINISTRATOR(Boolean ADMINISTRATOR) {
    this.ADMINISTRATOR = ADMINISTRATOR;
  }

  public User ACCOUNT_OWNER(Boolean ACCOUNT_OWNER) {
    this.ACCOUNT_OWNER = ACCOUNT_OWNER;
    return this;
  }

   /**
   * Get ACCOUNT_OWNER
   * @return ACCOUNT_OWNER
  **/
  
  public Boolean getACCOUNTOWNER() {
    return ACCOUNT_OWNER;
  }

  public void setACCOUNTOWNER(Boolean ACCOUNT_OWNER) {
    this.ACCOUNT_OWNER = ACCOUNT_OWNER;
  }

  public User ACTIVE(Boolean ACTIVE) {
    this.ACTIVE = ACTIVE;
    return this;
  }

   /**
   * Get ACTIVE
   * @return ACTIVE
  **/
  
  public Boolean getACTIVE() {
    return ACTIVE;
  }

  public void setACTIVE(Boolean ACTIVE) {
    this.ACTIVE = ACTIVE;
  }

  public User DATE_CREATED_UTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
    return this;
  }

   /**
   * Get DATE_CREATED_UTC
   * @return DATE_CREATED_UTC
  **/
  
  public OffsetDateTime getDATECREATEDUTC() {
    return DATE_CREATED_UTC;
  }

  public void setDATECREATEDUTC(OffsetDateTime DATE_CREATED_UTC) {
    this.DATE_CREATED_UTC = DATE_CREATED_UTC;
  }

  public User DATE_UPDATED_UTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
    return this;
  }

   /**
   * Get DATE_UPDATED_UTC
   * @return DATE_UPDATED_UTC
  **/
  
  public OffsetDateTime getDATEUPDATEDUTC() {
    return DATE_UPDATED_UTC;
  }

  public void setDATEUPDATEDUTC(OffsetDateTime DATE_UPDATED_UTC) {
    this.DATE_UPDATED_UTC = DATE_UPDATED_UTC;
  }

  public User USER_CURRENCY(String USER_CURRENCY) {
    this.USER_CURRENCY = USER_CURRENCY;
    return this;
  }

   /**
   * Get USER_CURRENCY
   * @return USER_CURRENCY
  **/
  
  public String getUSERCURRENCY() {
    return USER_CURRENCY;
  }

  public void setUSERCURRENCY(String USER_CURRENCY) {
    this.USER_CURRENCY = USER_CURRENCY;
  }

  public User CONTACT_DISPLAY(String CONTACT_DISPLAY) {
    this.CONTACT_DISPLAY = CONTACT_DISPLAY;
    return this;
  }

   /**
   * Get CONTACT_DISPLAY
   * @return CONTACT_DISPLAY
  **/
  
  public String getCONTACTDISPLAY() {
    return CONTACT_DISPLAY;
  }

  public void setCONTACTDISPLAY(String CONTACT_DISPLAY) {
    this.CONTACT_DISPLAY = CONTACT_DISPLAY;
  }

  public User CONTACT_ORDER(String CONTACT_ORDER) {
    this.CONTACT_ORDER = CONTACT_ORDER;
    return this;
  }

   /**
   * Get CONTACT_ORDER
   * @return CONTACT_ORDER
  **/
  
  public String getCONTACTORDER() {
    return CONTACT_ORDER;
  }

  public void setCONTACTORDER(String CONTACT_ORDER) {
    this.CONTACT_ORDER = CONTACT_ORDER;
  }

  public User TASK_WEEK_START(Integer TASK_WEEK_START) {
    this.TASK_WEEK_START = TASK_WEEK_START;
    return this;
  }

   /**
   * Get TASK_WEEK_START
   * @return TASK_WEEK_START
  **/
  
  public Integer getTASKWEEKSTART() {
    return TASK_WEEK_START;
  }

  public void setTASKWEEKSTART(Integer TASK_WEEK_START) {
    this.TASK_WEEK_START = TASK_WEEK_START;
  }

  public User INSTANCE_ID(Long INSTANCE_ID) {
    this.INSTANCE_ID = INSTANCE_ID;
    return this;
  }

   /**
   * Get INSTANCE_ID
   * @return INSTANCE_ID
  **/
  
  public Long getINSTANCEID() {
    return INSTANCE_ID;
  }

  public void setINSTANCEID(Long INSTANCE_ID) {
    this.INSTANCE_ID = INSTANCE_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.USER_ID, user.USER_ID) &&
        Objects.equals(this.CONTACT_ID, user.CONTACT_ID) &&
        Objects.equals(this.FIRST_NAME, user.FIRST_NAME) &&
        Objects.equals(this.LAST_NAME, user.LAST_NAME) &&
        Objects.equals(this.TIMEZONE_ID, user.TIMEZONE_ID) &&
        Objects.equals(this.EMAIL_ADDRESS, user.EMAIL_ADDRESS) &&
        Objects.equals(this.EMAIL_DROPBOX_IDENTIFIER, user.EMAIL_DROPBOX_IDENTIFIER) &&
        Objects.equals(this.EMAIL_DROPBOX_ADDRESS, user.EMAIL_DROPBOX_ADDRESS) &&
        Objects.equals(this.ADMINISTRATOR, user.ADMINISTRATOR) &&
        Objects.equals(this.ACCOUNT_OWNER, user.ACCOUNT_OWNER) &&
        Objects.equals(this.ACTIVE, user.ACTIVE) &&
        Objects.equals(this.DATE_CREATED_UTC, user.DATE_CREATED_UTC) &&
        Objects.equals(this.DATE_UPDATED_UTC, user.DATE_UPDATED_UTC) &&
        Objects.equals(this.USER_CURRENCY, user.USER_CURRENCY) &&
        Objects.equals(this.CONTACT_DISPLAY, user.CONTACT_DISPLAY) &&
        Objects.equals(this.CONTACT_ORDER, user.CONTACT_ORDER) &&
        Objects.equals(this.TASK_WEEK_START, user.TASK_WEEK_START) &&
        Objects.equals(this.INSTANCE_ID, user.INSTANCE_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(USER_ID, CONTACT_ID, FIRST_NAME, LAST_NAME, TIMEZONE_ID, EMAIL_ADDRESS, EMAIL_DROPBOX_IDENTIFIER, EMAIL_DROPBOX_ADDRESS, ADMINISTRATOR, ACCOUNT_OWNER, ACTIVE, DATE_CREATED_UTC, DATE_UPDATED_UTC, USER_CURRENCY, CONTACT_DISPLAY, CONTACT_ORDER, TASK_WEEK_START, INSTANCE_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    USER_ID: ").append(toIndentedString(USER_ID)).append("\n");
    sb.append("    CONTACT_ID: ").append(toIndentedString(CONTACT_ID)).append("\n");
    sb.append("    FIRST_NAME: ").append(toIndentedString(FIRST_NAME)).append("\n");
    sb.append("    LAST_NAME: ").append(toIndentedString(LAST_NAME)).append("\n");
    sb.append("    TIMEZONE_ID: ").append(toIndentedString(TIMEZONE_ID)).append("\n");
    sb.append("    EMAIL_ADDRESS: ").append(toIndentedString(EMAIL_ADDRESS)).append("\n");
    sb.append("    EMAIL_DROPBOX_IDENTIFIER: ").append(toIndentedString(EMAIL_DROPBOX_IDENTIFIER)).append("\n");
    sb.append("    EMAIL_DROPBOX_ADDRESS: ").append(toIndentedString(EMAIL_DROPBOX_ADDRESS)).append("\n");
    sb.append("    ADMINISTRATOR: ").append(toIndentedString(ADMINISTRATOR)).append("\n");
    sb.append("    ACCOUNT_OWNER: ").append(toIndentedString(ACCOUNT_OWNER)).append("\n");
    sb.append("    ACTIVE: ").append(toIndentedString(ACTIVE)).append("\n");
    sb.append("    DATE_CREATED_UTC: ").append(toIndentedString(DATE_CREATED_UTC)).append("\n");
    sb.append("    DATE_UPDATED_UTC: ").append(toIndentedString(DATE_UPDATED_UTC)).append("\n");
    sb.append("    USER_CURRENCY: ").append(toIndentedString(USER_CURRENCY)).append("\n");
    sb.append("    CONTACT_DISPLAY: ").append(toIndentedString(CONTACT_DISPLAY)).append("\n");
    sb.append("    CONTACT_ORDER: ").append(toIndentedString(CONTACT_ORDER)).append("\n");
    sb.append("    TASK_WEEK_START: ").append(toIndentedString(TASK_WEEK_START)).append("\n");
    sb.append("    INSTANCE_ID: ").append(toIndentedString(INSTANCE_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

