/*
 * Insightly API v2.2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.insightly.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;


import java.io.Serializable;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import javax.xml.bind.annotation.*;

/**
 * UserFollow
 */
@JacksonXmlRootElement(localName = "UserFollow")
@XmlRootElement(name = "UserFollow")
@XmlAccessorType(XmlAccessType.FIELD)
public class UserFollow implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("RECORD_TYPE")
  @JacksonXmlProperty(localName = "RECORD_TYPE")
  @XmlElement(name = "RECORD_TYPE")
  private String RECORD_TYPE = null;

  @JsonProperty("RECORD_ID")
  @JacksonXmlProperty(localName = "RECORD_ID")
  @XmlElement(name = "RECORD_ID")
  private Long RECORD_ID = null;

  public UserFollow RECORD_TYPE(String RECORD_TYPE) {
    this.RECORD_TYPE = RECORD_TYPE;
    return this;
  }

   /**
   * Get RECORD_TYPE
   * @return RECORD_TYPE
  **/
  
  public String getRECORDTYPE() {
    return RECORD_TYPE;
  }

  public void setRECORDTYPE(String RECORD_TYPE) {
    this.RECORD_TYPE = RECORD_TYPE;
  }

  public UserFollow RECORD_ID(Long RECORD_ID) {
    this.RECORD_ID = RECORD_ID;
    return this;
  }

   /**
   * Get RECORD_ID
   * @return RECORD_ID
  **/
  
  public Long getRECORDID() {
    return RECORD_ID;
  }

  public void setRECORDID(Long RECORD_ID) {
    this.RECORD_ID = RECORD_ID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserFollow userFollow = (UserFollow) o;
    return Objects.equals(this.RECORD_TYPE, userFollow.RECORD_TYPE) &&
        Objects.equals(this.RECORD_ID, userFollow.RECORD_ID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RECORD_TYPE, RECORD_ID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserFollow {\n");
    
    sb.append("    RECORD_TYPE: ").append(toIndentedString(RECORD_TYPE)).append("\n");
    sb.append("    RECORD_ID: ").append(toIndentedString(RECORD_ID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

